### ISSUE TITLE
Communication tools

### ISSUE THREAD

**Issue by zerok** [pytube/pytube#101]
During the #pycon2016 sprints we've used the conference's Slack. Now that the sprints are over what should our primary communication tool be? Should we perhaps use Gitter or something like that? Given that we use Github for pretty much everything here, it would kind of make sense :)

**Comment by codersquid** [comment]
Let me know if you use another slack. Enable the irc gateway too. I use weechat and add slacks to it just like other irc networks.

I think also a mailing list is good, and you can use pyvideo-data @ python.org if you like. I can add more admins. If you want a new something python.org address, they are friendly about setting them up.

Don't forget to keep a means of contact prominent on the site so that people can ask for help. People should be able to use public means and also have a direct email address to use as well for sensitive help.

**Comment by logston** [comment]
Hey @zerok, good point. I've gone ahead and started a gitter room for this repo and the data repo. 
https://gitter.im/pytube/pytube
https://gitter.im/pytube/data

@codersquid I agree. I vote that the mailing list sticks around and we use and publish that as the email to contact regarding data issues.

**Comment by logston** [comment]
Closing because we have a designated communication tool now. Please reopen if you feel parts of this issue where not fully addressed.

**Comment by zerok** [comment]
Awesome, thank you 🙂
