### ISSUE TITLE
[BUG] Channel can't get title  because initial_data not has key name 'sidebar'

### ISSUE THREAD

**Issue by birsbear** [pytube/pytube#1020]
I want to get the channel's title  and try to download the videos
```python
from pytube import Channel 

c = Channel("https://www.youtube.com/channel/UCHilzfET9Mh0DDYEnSHaeUg")
c.title
```
When i run this code to get title , i get some error:

```python
Traceback (most recent call last):

  File "C:\Users\tis05\Anaconda3\lib\site-packages\pytube\contrib\untitled1.py", line 15, in <module>
    c.title

  File "C:\Users\tis05\Anaconda3\lib\site-packages\pytube\contrib\playlist.py", line 315, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][

  File "C:\Users\tis05\Anaconda3\lib\site-packages\pytube\contrib\playlist.py", line 69, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][

KeyError: 'sidebar'
```
I check the `initial_data` found there is not Key "sidebar" inside
The "title" is in `initial_data['metadata']['channelMetadataRenderer']`

---
**System information**
python - 3.7
pytube - 10.8.4
pip install pytube

**Comment by tfdahlin** [comment]
Hi, this is an issue that I'm hoping to address sometime soon when I get the chance to do a rewrite of some of the code base. When I first wrote the `Channel` object, I made it inherit from the `Playlist` object because of significant code overlap. As a result of that, it has a `title` property when it should not. For the time being, please use `c.channel_name` to get the channel name.

**Comment by birsbear** [comment]
@tfdahlin  Thanks for recommend, but there is new problem 
when i call 
```python
c = Channel("https://www.youtube.com/channel/UCHilzfET9Mh0DDYEnSHaeUg")
c.channel_name
```  
the response show me 
``` python
Traceback (most recent call last):

  File "<ipython-input-4-6d9297730a0e>", line 1, in <module>
    c.channel_name

AttributeError: 'Channel' object has no attribute 'channel_name'
```

**Comment by tfdahlin** [comment]
Oh, that's... Actually my fault. I must have forgotten to create a new release after the most recent commit. I will hopefully be creating a new release in the next day or two with a fix for the current 404 problem, and that attribute will exist when I do so. For the time being, if you install from source with `python -m pip install git+https://github.com/pytube/pytube` (you may need to uninstall pytube first for this to work), then you should have the un-published version which has the `channel_name` attribute. Otherwise, I will hopefully have a resolution for the 404 issue soon, at which point I will publish a new package to pypi, and the fix for this problem will be a part of that package.

**Comment by birsbear** [comment]
OK i find the change in Channel.py  
I can use `c.channel_name` now
Thanks for recommend

**Comment by tfdahlin** [comment]
v10.8.5 was just released, and now has the `.channel_name` attribute, so I'm going to close this issue now.

**Comment by johann-lau** [comment]
This error also occurs when I use channel views and many other properties.
