### ISSUE TITLE
[BUG] Will the 404 error bug fix itself for functionallity of previous versions?

### ISSUE THREAD

**Issue by leifadev** [pytube/pytube#1027]
A quick "bug" question per se here.

As of recently it seemed you needed to push out an update to fix a 404 error regarding youtubers (private?) API having part of it being shutdown. Maybe I am incorrect on this, as I am recalling from a big thread yesterday talking about the whole thing.

I have previous binaries compiled with pytube 10.8.3 for example, and I am wondering the logistics of what exactly happened. Is there potential for their API to fix itself and the update you had happened to be a workaround, rendered useless because all previous versions would work? Or is this something different.

Just wanted to know for decision making in the near future. Thanks!

Specs:
- Python version: 3.9.2
- Pytube version 10.8.5
- pip3 install pytube

**Comment by tfdahlin** [comment]
Hi @leifadev, generally when YouTube makes a change, they don't revert it, so previous versions of the library will most likely not work going forward. In fact, I anticipate that the current workaround will stop working before too long, so I am working on additional fallbacks.

Effectively the issue comes from the fact that this library relies on an undocumented YouTube API endpoint that was developed for certain YouTube apps. They have been actively migrating to a different endpoint (called innertube), so I anticipate that the `get_video_info` endpoint that we currently use will be completely disabled in the future, regardless of the additional parameters we pass in our requests. I don't want to say that it's impossible for older versions to work again, but I would not count on it happening.

**Comment by tfdahlin** [comment]
Closing this issue now due to inactivity; feel free to comment if you have additional questions.
