### ISSUE TITLE
.filesize method taking too long

### ISSUE THREAD

**Issue by rishabh3354** [pytube/pytube#1042]
Hi @tfdahlin, How are you doing. i have a doubt/suggestion

When i was trying to calculate size of all videos using stream.filter() method, then it is taking so long to calculate( for 30 youtube obj, its taking 15-20 sec to calculate, i already have pytube obj( which already took 30 sec for 30 video urls, not a problem , it is fine), then why this filter query request is taking too long calculate the size of videos. i think it should not be a network request. i made a youtube downloader program and when i trying to calculate total size of videos, then it is responding after 15 sec and again requesting nwtwork call.

please suggest me how to calculate total size, because this approach is not worth it. 

```
resolution = "some resolution"
file_extension = "some file_extension"
# list of Youtube class objects -> youtube_obj

total_size = 0

for item in youtube_obj:
    yt = item.streams.filter(resolution=resolution, file_extension=file_extension).first()
    total_size += yt.filesize

print("size of all videos", total_size)
```

**Comment by tfdahlin** [comment]
@rishabh3354 this is because `.filesize` currently makes a web request. The filter part should not be taking very long, but the current implementation of `.filesize` makes an additional web request to find out how large the file is. I have a better method for this that will make this web request no longer necessary, which I will add when I am able to.

**Comment by rishabh3354** [comment]
@tfdahlin Thanks for the reply. Whenever you get the time, please fix this . Thanks for considering. Have a great day

**Comment by tfdahlin** [comment]
Working on this in #1045

**Comment by tfdahlin** [comment]
@rishabh3354 This should perform better now in v10.9.1. In most cases (but not necessarily all), pytube will now be able to extract the stream filesize from the manifest, which will prevent it from needing to make additional requests.

**Comment by rishabh3354** [comment]
> @rishabh3354 This should perform better now in v10.9.1. In most cases (but not necessarily all), pytube will now be able to extract the stream filesize from the manifest, which will prevent it from needing to make additional requests.

Thanks for the update. I just upgraded pytube. But still same condition for me.. it is taking 10-15 sec to count all the video size using filter. I think it is slightly better than previous version, but still taking time.. if anyhow could you make this that way so that a youtube object has all the information about the filesize, there is no need to call network request at all. If that is possible it would be a game changing thing for me.. but

anyways thanks for the update.

Have a great day ahead

**Comment by tfdahlin** [comment]
> When i was trying to calculate size of all videos using stream.filter() method, then it is taking so long to calculate( for 30 youtube obj, its taking 15-20 sec to calculate, i already have pytube obj( which already took 30 sec for 30 video urls, not a problem , it is fine), then why this filter query request is taking too long calculate the size of videos. i think it should not be a network request. i made a youtube downloader program and when i trying to calculate total size of videos, then it is responding after 15 sec and again requesting nwtwork call.

When you say that you already have pytube objects, how did you generate them? Is this coming from a playlist, for example? The reason that I ask is because pytube objects should be very quick to make, but may be slow to access information about. Most of the web requests are deferred until the very last minute when they become absolutely necessary. For example, if you do this:
```python
from pytube import YouTube
url = some_url
yt = YouTube(url)
```

Then the code will run very quickly because no web requests are being made. However, if you run the following code:
```python
from pytube import YouTube
url = some_url
yt = YouTube(url)
print(yt.title)
```
The code will run slowly, because pytube has to fetch the video title by making a web request.

Similarly, if you use playlists:
```python
from pytube import Playlist
p = Playlist(some_playlist_url)
for p in p.videos:
    print(p.watch_url)
```
This code will run quickly, because these are YouTube objects that have not downloaded any data, like in the above example where we only initialize the object without making web requests.

The only data (currently) that can be accessed without making web requests is the `watch_url`, `embed_url`, and `video_id`. In the future, I will be able to add some additional data in certain circumstances, like adding titles to videos in playlists. However, certain attributes (like stream filesize) cannot be determined without making additional web requests

**Comment by rishabh3354** [comment]
> > When i was trying to calculate size of all videos using stream.filter() method, then it is taking so long to calculate( for 30 youtube obj, its taking 15-20 sec to calculate, i already have pytube obj( which already took 30 sec for 30 video urls, not a problem , it is fine), then why this filter query request is taking too long calculate the size of videos. i think it should not be a network request. i made a youtube downloader program and when i trying to calculate total size of videos, then it is responding after 15 sec and again requesting nwtwork call.
> 
> When you say that you already have pytube objects, how did you generate them? Is this coming from a playlist, for example? The reason that I ask is because pytube objects should be very quick to make, but may be slow to access information about. Most of the web requests are deferred until the very last minute when they become absolutely necessary. For example, if you do this:
> 
> ```python
> from pytube import YouTube
> url = some_url
> yt = YouTube(url)
> ```
> 
> Then the code will run very quickly because no web requests are being made. However, if you run the following code:
> 
> ```python
> from pytube import YouTube
> url = some_url
> yt = YouTube(url)
> print(yt.title)
> ```
> 
> The code will run slowly, because pytube has to fetch the video title by making a web request.
> 
> Similarly, if you use playlists:
> 
> ```python
> from pytube import Playlist
> p = Playlist(some_playlist_url)
> for p in p.videos:
>     print(p.watch_url)
> ```
> 
> This code will run quickly, because these are YouTube objects that have not downloaded any data, like in the above example where we only initialize the object without making web requests.
> 
> The only data (currently) that can be accessed without making web requests is the `watch_url`, `embed_url`, and `video_id`. In the future, I will be able to add some additional data in certain circumstances, like adding titles to videos in playlists. However, certain attributes (like stream filesize) cannot be determined without making additional web requests

Yeah thanks. Okay now i will have to change my approach for calculating file sizes.  Anyways thanks for the message
