### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by zerok** [pytube/pytube#112]
Right now the site is running on github pages which is awesome for getting started but will eventually require from us to do more and more hacks. I'm thinking mostly about issues like redirecting which are normally handled using nginx et al. 

Should we perhaps try to get a tiny sponsored VPS where we simply put nginx on? I would love to keep the infrastructure we have to manage ourselves to be bare minimum but there is only so much we can do right now with github pages. 

Alternatively we could also try to use something like [Caddy](https://caddyserver.com/) and use Heroku or something similar for hosting.

What do you think?

**Comment by codersquid** [comment]
I also think it's a good idea for FLOSS reasons.

I think we could get resources from the PSF, #12.

If not, pyvideo has a rackspace account and they donate it to us. It is hosted there, and I could set up more rackspace user accounts so that people could spin up VMs. People will need to be careful not to spin up too many resources. Occasionally I get a large bill. They are really good about reversing the charges, but sometimes it is very inconvenient for me.

**Comment by logston** [comment]
I agree that, at some point, we may need to deploy to a VPS. Right now though, I don't think we've hit that point. Is there a particular hard-to-pass roadblock we are facing that would be gone if we were to get a VPS now? I know @elzilrac was working on URL redirection and it seemed that we could do so relatively easily without using Nginx; just a matter of a Pelican plugin. Also, since we have resources via @codersquid and plenty of offers from the PSF,  etc., I think we'll have the VPS when we come to need it. TL;DR. I think it might be a bit early to start looking for a VPS.

**Comment by logston** [comment]
Happy to revisit this issue when we start to hit growing pains. Please reopen if we are experiencing those pains now.
