### ISSUE TITLE
Suggestion: Talk to PSF about getting infrastructure sponsorship

### ISSUE THREAD

**Issue by codersquid** [pytube/pytube#12]
This year the PSF created a role for an IT person, and he's onboarding and handling their current infrastructure. Once the existing infrastructure work settles down, you could make a request.

This issue tracks the idea of making a grant proposal to the PSF for hosting of the pytube infrastructure.

**Comment by logston** [comment]
You make a great point @codersquid, that we should reach out to the PSF for money (via a grant) or infrastructure (if we need metal). However, since we are not at that point yet, and I'd like to focus people's efforts on pytube/data, I'm going to close this ticket. Please reopen if you feel differently.
