### ISSUE TITLE
[BUG]KeyError: 'streamingData'

### ISSUE THREAD

**Issue by 215561238** [pytube/pytube#1290]
**Describe the bug**
When I download a video, I always see this error in the same video

**To Reproduce**
Please provide the following information:
- https://www.youtube.com/watch?v=KG6NURQLex0&list=PLLvFTmqIwIbQBqgocaYhGYTym3_fAfB19&index=11
- st = yt.streams.get_highest_resolution()

**Output**
Traceback (most recent call last):
  File "d:\filePython\demo4.py", line 82, in <module>
    st = yt.streams.get_highest_resolution()  
  File "d:\filePython\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "d:\filePython\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "d:\filePython\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']

**System information**
Please provide the following information:
- Python version Python 3.10.1
- Pytube version '12.0.0'
- Command used to install pytube

**Comment by 215561238** [comment]
I tried to upgrade, but it still didn't work

**Comment by kinshuk-h** [comment]
The video in concern is age-restricted, and requires a login before any information about the same can be accessed (Age-restricted status can be verified by checking the value of the `age_restricted` property getter on the `YouTube` object).

User authentication details can be provided for bypassing this restriction by passing `use_oauth=True` when initialising the `YouTube` object. (More information is available on the same in the [docs](https://pytube.io/en/latest/user/quickstart.html?highlight=authentication))

The error is not due to a bug, but due to restrictions imposed by YouTube on age-restricted content.

**Comment by 215561238** [comment]
thank you

**Comment by SAIVENKATARAJU** [comment]
Hi @kinshuk-h 
Do you have any idea what is the expiry date for the OAUTH, is there any expiry date. Also, is there any way to authenticate through script. instead manually entering the code

**Comment by MaxWolf-01** [comment]
> The error is not due to a bug, but due to restrictions imposed by YouTube on age-restricted content.

Shouldn't `AgeRestrictedError` be raised here, since it states that: """Video is age restricted, and cannot be accessed without OAuth."""?

In the `bypas_age_gate` method, the `playability_status` is `LOGIN_REQUIRED` but the exception is only thrown if it is "`UNPLAYABLE`" which is confusing imo.

What's the reasoning behind this? And when is a video "unplayable" due to age-restrictions, isn't that already the case if login is required?

**Comment by 0xFA709394** [comment]
pytube 12.1.3
python 3.10.11

This bug still exists, has anybody figured out how to resolved this issue?

  ```
 yt.streams.filter(file_extension='mp4', progressive=True).order_by('resoluti
on').desc().first().download(output_path)
  File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 2
96, in streams
    return StreamQuery(self.fmt_streams)
  File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
76, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
61, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```

**Comment by Suro-One** [comment]
> pytube 12.1.3 python 3.10.11
> 
> This bug still exists, has anybody figured out how to resolved this issue?
> 
> ```
> yt.streams.filter(file_extension='mp4', progressive=True).order_by('resoluti
> on').desc().first().download(output_path)
> File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 2
> 96, in streams
>   return StreamQuery(self.fmt_streams)
> File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
> 76, in fmt_streams
>   stream_manifest = extract.apply_descrambler(self.streaming_data)
> File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
> 61, in streaming_data
>   return self.vid_info['streamingData']
> KeyError: 'streamingData'
> ```

**A quick fix:**
Open the __main__.py file in the pytube library (in your case just navigate to _D:\Program Files\Python310\lib\site-packages\pytube\__main__.py_
Go to line 161, which contains the statement return self.vid_info['streamingData'].

Update the line to check if the key 'streamingData' is present in the vid_info dictionary before returning it. You can use the dict.get() method to safely access the dictionary without raising a KeyError. Here's an example fix:

`return self.vid_info.get('streamingData', {})
`
This will return an empty dictionary {} if the key 'streamingData' is not present in vid_info, instead of raising a KeyError.
Doing so fixed the bug for me. 
@suxinde2009 @215561238  @kinshuk-h  @SAIVENKATARAJU

**Comment by JustThisWeeb** [comment]
> > pytube 12.1.3 python 3.10.11
> > This bug still exists, has anybody figured out how to resolved this issue?
> > ```
> > yt.streams.filter(file_extension='mp4', progressive=True).order_by('resoluti
> > on').desc().first().download(output_path)
> > File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 2
> > 96, in streams
> >   return StreamQuery(self.fmt_streams)
> > File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
> > 76, in fmt_streams
> >   stream_manifest = extract.apply_descrambler(self.streaming_data)
> > File "D:\Program Files\Python310\lib\site-packages\pytube\__main__.py", line 1
> > 61, in streaming_data
> >   return self.vid_info['streamingData']
> > KeyError: 'streamingData'
> > ```
> 
> **A quick fix:** Open the **main**.py file in the pytube library (in your case just navigate to _D:\Program Files\Python310\lib\site-packages\pytube__main__.py_ Go to line 161, which contains the statement return self.vid_info['streamingData'].
> 
> Update the line to check if the key 'streamingData' is present in the vid_info dictionary before returning it. You can use the dict.get() method to safely access the dictionary without raising a KeyError. Here's an example fix:
> 
> `return self.vid_info.get('streamingData', {}) ` This will return an empty dictionary {} if the key 'streamingData' is not present in vid_info, instead of raising a KeyError. Doing so fixed the bug for me. @suxinde2009 @215561238 @kinshuk-h @SAIVENKATARAJU


I tried this fix but it didn't really fix anything. Instead it made things even worse since now the exception is about 'videoDetails'

**Comment by Lexonight1** [comment]
using oauth in the youtube(use_oauth=True, allow_oauth_cache=True) register device

**Comment by rvpersie** [comment]
> using oauth in the youtube(use_oauth=True, allow_oauth_cache=True) register device

This seems to resolve the problem, it seems that this data stream error appears due to some age restriction permission, it is definitely a permission issue.

**Comment by Tarufetti** [comment]
> using oauth in the youtube(use_oauth=True, allow_oauth_cache=True) register device

this solved the problem of the StreamingData error, but raises a new problem.

I just don't want people that use my program to be forced to 'log in' just to download a video

**Comment by rvpersie** [comment]
> 

The issue is that due to certain restriction on specific videos you are unable to access video unless you are authenticated. For this reason, you need to first login to your gmail account for youtube and then run the script. And in order to do that you need to pass these parameters  (use_oauth=True, allow_oauth_cache=True). But i confirm that this work around works like a charm. Incredible i spent like 3-4 hours trying to figure it out.

**Comment by hazadus** [comment]
> using oauth in the youtube(use_oauth=True, allow_oauth_cache=True) register device

This is great, but how to do it if I use `pytube` in the Celery task on remote server?..

`pytube` worked great for me for about month without any auth, but now, unfortunatelly, I can't download even videos which worked before...

**Comment by pratikCMEX** [comment]
@hazadus 
Right, It was correctly worked, unfortunately, it is giving an error now. I have a script for downloading audio from youtube. Giving an error now.

**Comment by angelwayne** [comment]
> using oauth in the youtube(use_oauth=True, allow_oauth_cache=True) register device

Esto me funciono a la perfeccion, Gracias
