### ISSUE TITLE
"get_highest_resolution()" is broken

### ISSUE THREAD

**Issue by baptiste-g-etu** [pytube/pytube#1301]
Hello, i use pytube 12.0.0 and when I use the function "get_highest_resolution()" with a 1080p video, it returns a 720p video
```
import pytube
videolink = input('Entrez le lien de la vidéo: ')
video = pytube.YouTube(videolink)

MaxVideoResolution =video.streams.get_highest_resolution()
print(MaxVideoResolution)
```
Console : 
<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2" progressive="True" type="video">

But if i only put : `print(video.streams)` I have somewhere in the console:
<Stream: itag="299" mime_type="video/mp4" res="1080p" fps="60fps" vcodec="avc1.64002a" progressive="False" type="video">

I can download the video with 1080p by using a filter, but the function is useless and wrong. Can you help me?``

**Comment by rickyrorton** [comment]
get_highest_resolution will get the highest resolution PROGRESSIVE stream not the highest resolution stream overall
This is not a bug it is intentional please read the documentation before creating an issue
![image](https://user-images.githubusercontent.com/74890659/164896602-af97af3c-d1ae-475c-a82e-29edc67b317d.png)

**Comment by baptiste-g-etu** [comment]
ah ok thanks
