### ISSUE TITLE
fix bar progress display

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1377]
```diff
remaining = max_width - filled
progress_bar = ch * filled + " " * remaining
percent = round(100.0 * bytes_received / float(filesize), 1)
-text = f" ↳ |{progress_bar}| {percent}% \r"
+text = f" ↳ |{progress_bar}| {percent}% \n"
sys.stdout.write(text)
sys.stdout.flush()
```

**Comment by rcsmit** [comment]
Why would you do this? You get multiple lines now

Downloading.... Patrick Bruel - J'te l'dis quand même - Pauline  The Voice 2022  Demi-finale
 ↳ |█████████████████████████                                                    | 32.3%  (1.0/3.1 MB)
 ↳ |██████████████████████████████████████████████████                           | 64.7%  (2.0/3.1 MB)
 ↳ |███████████████████████████████████████████████████████████████████████████  | 97.0%  (3.0/3.1 MB)
 ↳ |█████████████████████████████████████████████████████████████████████████████| 100.0%  (3.1/3.1 MB)

instead of

Downloading.... Patrick Bruel - J'te l'dis quand même - Pauline  The Voice 2022  Demi-finale
Filesize = 3.09 MB)██████████████████████████████████████████████████████████████| 100.0%  (3.1/3.1 MB)

(code is slightly different, it's about the idea)

**Comment by ghost** [comment]
@rcsmit 

hello, 

Downloading Vídeos curtos e engraçados 18 | File size: 1.78 MB
 ↳ |██████████████████████████████████████████████████████████████████████████| 100.0%
Downloading O VIDEO QUE VOCÊ TALVEZ  PRECISE VER! (REFLEXÃO) | File size: 3.86 MB
 ↳ |██████████████████████████████████████████████████████████████████████████| 100.0%

here appears a progress bar for each video (playlist)
