### ISSUE TITLE
[BUG] Cannot download video, pytube crashes

### ISSUE THREAD

**Issue by Shoter3000** [pytube/pytube#1726]
I am trying to download the video, but the program returns an error, even though all the links are correct.
[Output.txt](https://github.com/pytube/pytube/files/12043531/Output.txt)
[Code.txt](https://github.com/pytube/pytube/files/12043544/Code.txt)

Information:
- Python version: Python 3.11.4
- Pytube version: pytube 15.0.0
- Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube
- PIP LIST:
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
coverage           5.5
decorator          4.4.2
deprecation        2.1.0
eyed3              0.9.7
filetype           1.2.0
idna               3.4
imageio            2.31.1
imageio-ffmpeg     0.4.8
moviepy            1.0.3
numpy              1.25.0
packaging          23.1
Pillow             10.0.0
pip                23.1.2
proglog            0.1.10
pytube             15.0.0
requests           2.31.0
setuptools         65.5.0
toml               0.10.2
tqdm               4.65.0
typing_extensions  4.7.1
urllib3            2.0.3

**Comment by 24makee** [comment]
Hey @Shoter3000 

I ran the code you uploaded in this issue, but I am not getting the same error. On my side the error comes from the next line ```mp4_video.close()``` because the 'YouTube' object has no attribute 'close'. 

From the output it seems that it was a 410 HTTP error, error which is really close to the 404 Not Found error. You can check the difference between them online if interested, but both of them mean that you are requesting something that does not exist anymore.

Also, I noticed that Python is installed from Windows App Store, I strongly recommend avoiding installing Python from Windows App Store because it has a lot of bugs, myself encountering a big problem with the pip that comes with the Python installed from there. The best place to get Python is from python.org. Maybe you should try replacing your current Python with the one from python.org before checking anything else.

If you are still getting errors, can you try running the same code that you uploaded here in the .txt file for let's say 3 videos and attach each output here? It would be really useful. Also, when uploading the outputs please wrap them between ``` pairs and not upload text files.

Cheers

**Comment by Shoter3000** [comment]
Hello @24makee 
Problem was solved with Python installed from python.org. Then I changed the code too and now it's working.
Thank you
```
def download_file():
    #download video
    mp4_video = YouTube(get_link).streams.get_highest_resolution().download()
    vid_clip = VideoFileClip(mp4_video)
    vid_clip.close()
    #move to selected directory
    shutil.move(mp4_video, user_path)
