### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)

### ISSUE THREAD

**Issue by boostup** [pytube/pytube#176]
Hi,

First many thanks for your work on this project!  So useful!

I'm using your package through a .py file which is executed by Nodejs as following:

```
var spawn = require('child_process').spawn;  
scriptExecution = spawn('python', ["./download_one_with_pytube.py", urlObj.url]);
```

However, the error is a Python one, inside the captions.py even though all works well for video downloads.

I've never coded with Python before, however it seems I getting an error due to some ascii issue.

I have found [this about unicode in the Python doc](https://docs.python.org/2.7/howto/unicode.html#the-unicode-type) as a starting point, but I guess that would mean I need to perform some modification in the Python source code.

So, what I'm asking from you is simple:  do you believe this is the solution to THIS problem?  If so I'll give it a try as I have forked your repo, but since I'm new to Python, I'm looking for a litte guidance from the PRO ;)  

Thanks a lot and kindregards,
Fred

**Here are the prints and errors I get in the terminal window:**

```
There are 22 streams available

<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">
Available captions
[
Traceback (most recent call last):
  File "./download_one_with_pytube.py", line 18, in <module>

    print available_captions
  File "/Users/boostup/Library/Python/2.7/lib/python/site-packages/pytube/captions.py", line 84, in __repr__
    return'<Caption lang="{s.name}" code="{s.code}">'.format(s=self)

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)

Process quit with code : 1
```

**Here is the simple code I'm running:**

**filename:**_download_one_with_pytube.py_

```
import sys
import json
from pytube import YouTube

video_url = "https://www.youtube.com/watch?v=IY08bPFjIUY"
yt = YouTube(video_url)

print "There are %d streams available\n" %yt.streams.count()
available_streams = yt.streams.filter(resolution="360p", subtype='mp4').asc()

for stream in available_streams.all():
    print stream

print "Available captions"
available_captions =  yt.captions.all()
```

**Comment by boostup** [comment]
Oh, I also wanted to add that when I use the 'caption = yt.captions.get_by_language_code('en')' method, I get the captions without errors; it is only when I try to get the list of available captions that I get this error.  But I do need to get the list of available langs so that I can programmatically choose the right language. 

Thanks!

**Comment by boostup** [comment]
Can anyone help at all?

**Comment by ddoyaguez** [comment]
Hi,
I could not reproduce the issue with your code above because the Youtube video seems to be no longer available.
Anyway, trying your code with other videos make the variable 'available_captions' contain an empty list.

A possible workaround can be replacing line 84 of captions.py by:
`return unicode('<Caption lang="{s.name}" code="{s.code}">'.format(s=self), errors='ignore')`
This might solve the issue.

If you can provide another URL so i can reproduce the issue it would be very helpful.

EDIT: I have traced the code and in function initialize_caption_objects() in __main__.py, it enters the first if condition (line 186). This will make caption_tracks be always an empty list. So it looks like pytube no longer supports that caption system.

**Comment by ocervell** [comment]
I get the same error, with `pytube.helpers.safe_filename` when computing the filename for some videos.

Basically any video that have special language-specific characters in the title will be affected.
Try [this one](https://www.youtube.com/watch?v=eviqX3QXd-s) for an example.

Since it's impossible to account for all weird characters (from any language) present on Youtube, if you want to safely create a filename without losing information, you'll need to make a unique base64 encoded string for your filenames.

Of course you lose readability of filenames...

For anyone interested, this is how I patched `pytube` to generate unique b64-encoded filenames, so that I never run into the exception with downloading something:
```
import pytube
import base64
def safe_filename(s, max_length=255):
    return base64.urlsafe_b64encode(your_string)
pytube.helpers.safe_filename = safe_filename
```
