### ISSUE TITLE
Downloading playlist fails on age restricted videos

### ISSUE THREAD

**Issue by jamescurtis** [pytube/pytube#224]
self.js_url and self.js variable not set when downloading age_restricted videos, which cause an exception when line 40 of cipher.py is hit because js is None.

**Comment by billd100** [comment]
Also seeing this. Not just limited to playlists either. See this video: https://www.youtube.com/watch?v=T2aJzwAeA9Y

**Comment by billd100** [comment]
Also seeing this. Example here: https://www.youtube.com/watch?v=0RvMBo0e6PY. But not all age restricted videos throw the TypeError, see this video: https://www.youtube.com/watch?v=i6JTvzrpBy0.

`self.js` in `__main__.py` is always `None` for age restricted videos because we don't extract the js from the html of embedded videos. I think the assumption was that the url of embedded videos included the signature. This doesn't appear to always be the case (anymore?) and there seems to be no correlation with video quality. One solution is to fallback to extracting base.js for embedded videos without a signature in the url.

In the process of PR'ing this.
