### ISSUE TITLE
.download() filename removes commas

### ISSUE THREAD

**Issue by LiamGow** [pytube/pytube#236]
The Stream.download() function's filename argument, used to name the resulting file, removes commas from the string provided.

Below, you can see the cmd in which I call the function, with the comma in the filename.  Then, referring to the function code, you can see the filename is printed, with the comma.

![screenshot 54](https://user-images.githubusercontent.com/10949125/36958033-b3167862-1fed-11e8-8f24-fd1008fe5cdb.png)
![screenshot 52 - copy](https://user-images.githubusercontent.com/10949125/36958009-7eb5dd56-1fed-11e8-9ea4-ae9b7cb0a1b6.png)

The resulting file created in my directory, however, does not have a comma.  (The mp3 of the same name is the result of an earlier run in which I manually renamed the file to include the comma - please disregard it.)

![screenshot 52](https://user-images.githubusercontent.com/10949125/36958010-7ecb9380-1fed-11e8-8b8b-b6b39d65a11f.png)

**Comment by escherwd** [comment]
When pytube writes the file it discards some of the characters that could make the filename unsafe (like "." or "," in your case). 

If you really wanted the file to be renamed, you should first import safe_filename with
`from pytube.helpers import safe_filename`

Then you could find the path of the file after it's downloaded using
`name = (safe_filename(yt.title) + ".mp4")`
Which would turn out to be `Koko Kara Koko Kara.mp4`

Now that you know the exact name of the file and it's url, you can rename it to what you want. 

Also, using periods and commas and such is dangerous in filenames because `this if my.file` would seem like a file with a "file" extension to the computer which wouldn't be good.
