### ISSUE TITLE
Why audio streams is downloading to much slower then video?

### ISSUE THREAD

**Issue by nickmetal** [pytube/pytube#247]
python -V -> Python 3.6.3
macos sierra 10.13

How to reproduce:
**audio.py** ->
```
from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')
yt.streams.filter(only_audio=True).first().download()
```
```
$ time python audio.py 
#  output after 1 min 05 sec
python audio.py  0.52s user 0.11s system 0% cpu 1:05.82 total
```

**video.py** ->
```
from pytube import YouTube

stream = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0').streams.first()
assert stream.type == 'video'
stream.download()
```

```
$ time python video.py 
#  output after 8.46 sec
python video.py  0.94s user 0.24s system 13% cpu 8.463 total
```

Maybe you know. Is there are restrictions for audio streams downloading from youtube?

**Comment by nficano** [comment]
I believe this is related to how I wrote download chunking, can you please check the latest version see if the issue still persists?

**Comment by vn-ki** [comment]
I think this should be reopened. Youtube is indeed throttling DASH streams.

Relevant youtube-dl issue: https://github.com/rg3/youtube-dl/issues/15271

**Comment by rafaelmarques7** [comment]
I have the same issue with the latest version.

I tested it on two different instances, one where the music video is just an image, and another where the video is actually a video.
First case, A+V took 4 seconds, while downloading the audio only took 73.
Second case, A+V took 40 seconds, while audio only took 130.

It would be great if the audio downloads could be much faster, but hey, I am still happy with the library, and intend to use it, even though I only want the audio. I will probably download A+V and take the audio file afterwards.

**Comment by Cokemonkey11** [comment]
I'm seeing some downloads take a very long time - even 1:1 ratio of video duration to download duration

**Comment by FranzPio** [comment]
~~Apparently, the devs of youtube-dl have fixed this (relevant code: [https://github.com/CommanderRoot/youtube-dl/pull/29/commits/e4a60912b8345536387ae14d0d0611eb0b82c23a](https://github.com/CommanderRoot/youtube-dl/pull/29/commits/e4a60912b8345536387ae14d0d0611eb0b82c23a))
by using a chunk size of `10485760` bytes,
since~~ YouTube seems to throttle downloads of DASH streams at around >10MB chunk size,
as described here: [https://github.com/rg3/youtube-dl/issues/15271#issuecomment-362834889](https://github.com/rg3/youtube-dl/issues/15271#issuecomment-362834889).

EDIT: Changing the chunk size actually isn't sufficient. youtube_dl has methods to somehow intelligently determine the adequate chunk size after every downloaded chunk or even pause downloading for a few ms to circumvent throttling (see e.g. [here](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/common.py)).

**Comment by vn-ki** [comment]
I have the fix ready, but I can't find time to code it. In case anyone is interested, I can provide sample code.

**Comment by FranzPio** [comment]
I have never filed a pull request before (and therefore don't have any experience!), but since noone has come forward yet, I could at least try to fix this.

**Comment by StephaneDci** [comment]
> I have the fix ready, but I can't find time to code it. In case anyone is interested, I can provide sample code.

Hello, Could you please provide details I would be interested on how to fix it . Regards. Stéphane

**Comment by morgan-greywolf** [comment]
> I have the fix ready, but I can't find time to code it. In case anyone is interested, I can provide sample code.

Post the sample. I'm pretty sure I can code it.

**Comment by wilk85** [comment]
I have wroten a function which is getting only video/mp4 files, biggest problem is with downloading these files, it seems that streams.first().download() is going very fast, huge files and small are downloaded nicely, but when im using only download() it goes about 120-250kbps, and no sound to videos is provided, do you guys know how to fix that?

**Comment by RonenR** [comment]
FYI - just tested today with youtube-dl - and encountered the same: audio-only (in fact any DASH type download) takes much longer to download than the regular download.
