### ISSUE TITLE
pytube erroneously labels 4320p (8K) streams 2160p (4K)

### ISSUE THREAD

**Issue by FranzPio** [pytube/pytube#304]
YouTube seems to support 8K resolution videos (e.g. this one: [https://www.youtube.com/watch?v=1La4QzGeaaQ](https://www.youtube.com/watch?v=1La4QzGeaaQ)).

Nonetheless, pytube only outputs the following highest resolution streams:
```
[<Stream: itag="272" mime_type="video/webm" res="2160p" fps="30fps" vcodec="vp9">,
 <Stream: itag="313" mime_type="video/webm" res="2160p" fps="30fps" vcodec="vp9">,
 <Stream: itag="315" mime_type="video/webm" res="2160p" fps="60fps" vcodec="vp9">,
 <Stream: itag="337" mime_type="video/webm" res="2160p" fps="60fps" vcodec="vp9.2">,...
```
Note how the 2160p30 stream exists twice, though itag 272 is actually an 8K video.
The resolution should rather be `4320p` in this case.

**Comment by diegocr** [comment]
Good catch, but actually looks like what 272 holds could vary and be anything in the range 1440-4320p :thinking:

**Comment by wimpykid719** [comment]
I'm in same situation. How do I fix that?

**Comment by thatDudo** [comment]
YouTube is using itags for storing information about the video.
For example itag 5 stands for: resolution=240p, bitrate=64kbps, format=mp4.

From time to time YouTube changes their code and thus the itags, for example itag 272.
In this scenario pytube didn't changed the itag 272 needed for identification of 8k videos.
So if you want to fix it just update the **itag.py** file in your pytube directory (like: "%appdata%\Local\Programs\Python\Python38\
Lib\site-packages\pytube"), **and replace line 63: 
_272: ("2160p", None),_ with 
_272: ("4320p", None)_,**

But remember: This is a DASH video file. That means it will only contain video -> **no audio**
To get a video with audio, download the audio file and connect them using something like ffmpeg.

**Comment by wimpykid719** [comment]
Thank you for replay I find those line at itags.py.
and is it okay with 272 is same number?
if i chose get itag 272 which file will I get 2160 or 4320???

**Comment by thatDudo** [comment]
Sorry for the late reply. If i'm not wrong 2160p is represented by other itags like 313/315
see https://gist.github.com/sidneys/7095afe4da4ae58694d128b1034e01e2

**Comment by wimpykid719** [comment]
Thanks for reply I changed 272: ("2160p", None), to
272: ("4320p", None), But I didn't work. I checked all tags that I got from this movie.
https://www.youtube.com/watch?v=zCLOJ9j1k2Y&t=2s

And even I couldn't get itag: 272.
Insted of itag: 272 I got 313, 315 with res is 2160.

**Comment by wimpykid719** [comment]
<Stream: itag="313" mime_type="video/webm" res="2160p" fps="30fps" vcodec="vp9" progressive="False" type="video">, 
<Stream: itag="315" mime_type="video/webm" res="2160p" fps="60fps" vcodec="vp9" progressive="False" type="video">,

I think itag 315 is res 4320p 60fps and itag 313 is res 2160p 60fps. Because of 2160p fps30 is not exists this movie.
and I thought more difficult solve this problem fps also wrong.

**Comment by thatDudo** [comment]
**EDIT: pls look at my last message where you can find the latest fix**

Ok I should have tested the code before posting it here .-.
I tested it and the solution is to modify itags.py even further. And btw: itag 315 is 2160p --> https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f

The thing is: If you had had downloaded the correct itag video you would have gotten the correct 8k video anyway. You only modify it so that you get to know the correct information in python.

```
    100: ("360p", "128kbps"),
    101: ("480p", "192kbps"),
    102: ("720p", "192kbps"),
    132: ("240p", "48kbps"),
    151: ("720p", "24kbps"),
    300: ("720p", "128kbps"),  # <--- HERE
    301: ("1080p", "128kbps"), # <--- HERE
    # DASH Video
    133: ("240p", None),
    134: ("360p", None),
    135: ("480p", None),
    136: ("720p", None),
    137: ("1080p", None),
    138: ("2160p", None),
    160: ("144p", None),
    167: ("360p", None),
    168: ("480p", None),
    169: ("720p", None),
    170: ("1080p", None),
    212: ("480p", None),
    218: ("480p", None),
    219: ("480p", None),
    242: ("240p", None),
    243: ("360p", None),
    244: ("480p", None),
    245: ("480p", None),
    246: ("480p", None),
    247: ("720p", None),
    248: ("1080p", None),
    264: ("1440p", None),
    266: ("2160p", None),
    271: ("1440p", None),
    272: ("4320p", None), # <--- HERE
    278: ("144p", None),
    298: ("720p", None),
    299: ("1080p", None),
    302: ("720p", None),
    303: ("1080p", None),
    308: ("1440p", None),
    313: ("2160p", None),
    315: ("2160p", None),
    330: ("144p", None),
    331: ("240p", None),
    332: ("360p", None),
    333: ("480p", None),
    334: ("720p", None),
    335: ("1080p", None),
    336: ("1440p", None),
    337: ("2160p", None),
    398: ("720p", None),  # <--- HERE
    399: ("1080p", None), # <--- HERE
    400: ("1440p", None),
    401: ("2160p", None), # <--- HERE
    402: ("4320p", None), # <--- HERE
    # DASH Audio
    139: (None, "48kbps"),
    140: (None, "128kbps"),
    141: (None, "256kbps"),
    171: (None, "128kbps"),
    172: (None, "256kbps"),
    249: (None, "50kbps"),
    250: (None, "70kbps"),
    251: (None, "160kbps"),
    256: (None, "192kbps"), # <--- HERE
    258: (None, "384kbps"), # <--- HERE
    325: (None, None),
    328: (None, None),
}

HDR = [330, 331, 332, 333, 334, 335, 336, 337]
_60FPS = [272, 298, 299, 302, 303, 308, 315, 398, 399, 400, 401, 402] + HDR  # <--- HERE (Fixes FPS)
```


**Itag 402 is 4320p. And the video you choosed only offered 402 for 8k**. I would suggest you to look at https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f from time to time cause only thing that doesn't change is that everything changes.
Btw I've tested out **youtube-dl** recently and its probably a very good alternative to pytube because it is much faster and easier to use. It has everything that pytube and ffmpeg has and even more.

Hope I could help you this time...

Ps. It takes a very very long time to download 8k video -.-

**Comment by wimpykid719** [comment]
Oh thank you it worked.
But I don't know why were you able to fix this problem.
This is all I can just copy and paste your code. haha.

Did you read the all of the pytube code and understand.

It's really cool I want to be like you.

**Comment by wimpykid719** [comment]
and I really suprised youtube-dl has ffmpeg inside of the code??

youtube-dl installed then Can I use ffmpeg too??

**Comment by thatDudo** [comment]
Thank you, very nice xD

_To help you understand all of this mess: Every video format on youtube has its own identifier: the itag._

_The problem we were having here was that the programmer from google changed the itags and pytube didn't. 
--> Pytube didn't know some of the video formats from youtube and e.g. it interpreted a 8k video as 4k._

Thats the most important thing to understand here.

I only new what was probably wrong because I was so interested in finding out how to download videos from various websites like youtube or adultswim or whatever. And so I started to look at stackoverflow and found out how to do it manually and what role itags play.

Actually its not this complicated to download: 

1. download all the video information from http://www.youtube.com/get_video_info?video_id=POhsRpnErqA **and URL decode** don't worry you can read it when you decode it at a website like https://www.urldecoder.org/

2. Its json so extract video URL and you get something like this: https://r2---sn-h0jelne7.googlevideo.com/videoplayback?expire=1598486016&ei=oKFGX7LOApSc8gOwq7HQDQ&ip=2003%3Acb%3Acf46%3Ac569%3A9973%3Aa0%3A15fe%3Af8dd&id=o-AHsK1fmJb3IOdpXRHQuAxHZLcg2_OdwAbY67B5Fsg9be&itag=243&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=8p&mm=31%2C29&mn=sn-h0jelne7%2Csn-h0jeen76&ms=au%2Crdu&mv=m&mvi=2&pl=34&initcwndbps=1045000&vprv=1&mime=video%2Fwebm&gir=yes&clen=14514518&dur=702.268&lmt=1598412831381390&mt=1598464237&fvip=6&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgK1gvy1y6F9jr18Exeo8FvsJHwf65ZHjBdx2eeF4gNW4CIQCvniBcJ3KE2HcO0IfrHOAFKwCg6C8CztG8j7c8PV4sEA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPVdF3x2L5l_0c8kGjHhTXwChT2uplsUNIzB-RgpEwmdAiEAhawbv1467j3DyGg6wvw-GZdpWACuw1S3alwV3L23RBQ%3D&alr=yes&cpn=abiFwqO5r6IUWOUy&cver=2.20200825.04.00 
(Link will probably not work because it expires and is bound by ip-address)
3. Download it by using _right click_ or a program like wget and enjoy.

And about youtube-dl: I think you gotta download ffmpeg seperatly you can't use it in youtube-dl .-.

Well don't worry the fact alone that you are interested in such things as programming is pretty cool already. If you start doing more interesting projects you eventually start getting even better :D

**Comment by wimpykid719** [comment]
Sorry for late reply and Thank you so much for replying. I downloaded a video infomation then I was able to get a bunch of string I can't read it for a lot of infomation.
So you mean pytube is reading those string and get the information rigjt?
Is json so extract video URL including too this infomation string??

**Comment by RONNCC** [comment]
Hi @FranzPio & @wimpykid719,

Am closing issue as it has been quite a while -- feel free to reopen if issue still persist 😄 

Thanks

**Comment by arpitdiwan** [comment]
Hello @thatDudo and @wimpykid719  
Thank you @thatDudo for figuring out the solution.

But in this video --> https://www.youtube.com/watch?v=7LJIcrJKDI0&ab_channel=Jacob%2BKatieSchwarz 
It's a 8k video, it gives an unique itag 571 as you can see the stream data  when i printed out the all streams. The resolution is None, but I'm thinking this stream can be 8k (4320p). 

`<Stream: itag="571" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.17M.10.0.110.09.16.09.0" progressive="False" type="video">
`

**Comment by thatDudo** [comment]
Itags were updated yet again...

To make it clear now:
**You can download the video and it will be 8k**. The problem you're having is that pytubes itag.py file is not being held updated --> It doesn't show correct format to you even though it will be downloading the correct format.

**What it shows before fix:**

```
>>> yt.streams[2]
<Stream: itag="571" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.17M.10.0.110.09.16.09.0" progressive="False" type="video">                                                                                                      
>>> yt.streams[2].download()
'C:\\Users\\...\\Best of 8K HDR 60p (FUHD).mp4'
>>> ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "Best of 8K HDR 60p (FUHD).mp4"
7680x4320
```

**Fix:**

Here is an updated (but not perfect) version of my custom itag.py file:
[itags.txt](https://github.com/nficano/pytube/files/5652230/itags.txt) **--> Rename to .py**

Location:
%appdata%\Local\Programs\Python\PythonXX\Lib\site-packages\pytube\itags.py


**Output after fix:**

```
>>> yt.streams[2]
<Stream: itag="571" mime_type="video/mp4" res="4320p" fps="60fps" vcodec="av01.0.17M.10.0.110.09.16.09.0" progressive="False" type="video">
```

**Comment by RONNCC** [comment]
@tfdahlin

**Comment by tfdahlin** [comment]
I'll update it

**Comment by Raprodent** [comment]
There's no 2160p with audio?

**Comment by RONNCC** [comment]
@Raprodent  can you elaborate on your question?

**Comment by Raprodent** [comment]
Sure thing. Is there an iTag for 1440 / 2160 / 4320 that is combined with audio?

**Comment by RONNCC** [comment]
Hey @Raprodent  think we ran into the same thing https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f :-)

Since it's proprietary, I'm not sure either;

**Comment by Raprodent** [comment]
Thank you RONNCC !
There must be a workaround, it's a weird-ass implementation otherwise.
And that 720p has 192kbit audio while the rest is.. worse?

**Comment by RONNCC** [comment]
@Raprodent  happy to help with updating the itags file if it's out of date :-)

**Comment by Raprodent** [comment]
Sure, I'll try to contribute if I find anything, same goes for you with that 2160p with audio. :)
