### ISSUE TITLE
desc() function is not working i am getting 360p every time

### ISSUE THREAD

**Issue by schandan696** [pytube/pytube#331]
yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()

**Comment by silverstrangetech** [comment]
I checked a couple of test videos since you didn't supply a url.

This seems to be an issue with adaptive vs progressive streams. Adaptive videos only have video streams, while progressive steams have video and audio streams together. Right now, pytube doesn't support combining an adaptive video stream with an audio stream automatically.

From the README.md:
> You may notice that some streams listed have both a video codec and audio codec, while others have just video or just audio, this is a result of YouTube supporting a streaming technique called Dynamic Adaptive Streaming over HTTP (DASH).
> 
> In the context of pytube, the implications are for the highest quality streams; you now need to download both the audio and video tracks and then post-process them with software like FFmpeg to merge them.
> 
> The legacy streams that contain the audio and video in a single file (referred to as "progressive download") are still available, but only for resolutions 720p and below.

So the highest resolution progressive stream will at most be 720p, but it seems fairly common for the there to only be 360p and lower available.

The readme recommends using ffmpeg to combine a separate audio and video stream, and based on some quick research you should be able to combine audio and video streams with a single command:
`ffmpeg -i video.mp4 -i audio.m4a -c:v copy -c:a copy output.mp4`
