### ISSUE TITLE
'StreamQuery' object has no attribute 'download'

### ISSUE THREAD

**Issue by SKP1535** [pytube/pytube#344]
When I'm doing this it says 'StreamQuery' object has no attribute 'download'

`yt = link.streams.filter(only_audio=True, subtype='webm', abr='160kbps').download('Audiofile/')`

but when i use get_by_itag it works fine why?

`yt = link.streams.get_by_itag('251')`

a year back i was able to download the audio with filter module but not now why?

**Comment by Impulse-PW** [comment]
StreamQuery object holds a list of all of the different streams you can choose from. See: https://python-pytube.readthedocs.io/en/latest/api.html#streamquery-object

Contents of a StreamQuery object can be seen in the examples:
`[<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2">,
 <Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">,
 <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
 <Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">,
 <Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">,
 <Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028">,
 <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9">,
 <Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">,
 <Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9">,
 <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401e">,
 <Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9">,
 <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">,
 <Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9">,
 <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015">,
 <Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9">,
 <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c">,
 <Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9">,
 <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2">,
 <Stream: itag="171" mime_type="audio/webm" abr="128kbps" acodec="vorbis">,
 <Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus">,
 <Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus">,
 <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus">]`

Think of it like a list.

Usually calling ".first()" will give you the best stream given the filters you supply with the exception of Progressive streams having priority over Adaptive, even though Adaptive is higher quality. Since you're doing audio in the example that shouldn't be a concern, but good to know regardless.

Anyways, given that knowledge the solution is this: 

`yt = link.streams.filter(only_audio=True, subtype='webm', abr='160kbps').first().download('Audiofile/')`

**Comment by SKP1535** [comment]
Thanks a lot for quick reply

**Comment by Impulse-PW** [comment]
No problem =]

**Comment by manoj-nain** [comment]
i am facing same issue with playlist.

'StreamQuery' object has no attribute 'get_by_resolution'

`from pytube import Playlist
pl = Playlist("https://www.youtube.com/watch?v=Edpy1szoG80&list=PL153hDY-y1E00uQtCVCVC8xJ25TYX8yPU")
pl.download_all()`

**Comment by Alfacentauree** [comment]
yt = YouTube("https://www.youtube.com/watch?v=pFX65YC4u2Y")
stream = yt.streams.filter(subtype="mp4")
stream.get_by_resolution("240p").download()

i try to download it apears this msg : AttributeError: 'NoneType' object has no attribute 'download'

**Comment by Greko2017** [comment]
```python
Downloading: [<Stream: itag="135" mime_type="video/mp4" res="480p" fps="24fps" vcodec="avc1.4d4014" progressive="False" type="video">]
Traceback (most recent call last):
  File "playlist_downloader.py", line 18, in <module>
    stream.first().download('CodeIgniter/')
  File "D:\Perso Work\PYTUBE\.env\lib\site-packages\pytube\streams.py", line 247, in download
    bytes_remaining = self.filesize
  File "D:\Perso Work\PYTUBE\.env\lib\site-packages\pytube\streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "D:\Perso Work\PYTUBE\.env\lib\site-packages\pytube\request.py", line 200, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'

```

**Comment by rishabh3354** [comment]
This is the existing bug that no one wants to resolve, even they consider its not a bug

**Comment by juvtorg2014** [comment]
> This is the existing bug that no one wants to resolve, even they consider its not a bug

Set function first() to StreamQuery and all OK
