### ISSUE TITLE
CLI: can overwrite a downloaded file

### ISSUE THREAD

**Issue by stdedos** [pytube/pytube#369]
A call like this:

```bash
pytube https://www.youtube.com/watch?v=video --itag=x
pytube https://www.youtube.com/watch?v=video --itag=y
```

Will surely overwrite a downloaded file. Would it be wise to add some no-clobber check by default?

**Comment by Hummus-Ful** [comment]
It seems like an easy fix by adding `isfile` check in streams.py file:
```
# fp = file_path
if os.path.isfile(fp):
    return fp
```

My only concern is if the last downloaded file was aborted.

I can open a pull request if @nficano approves this issue

**Comment by erdincay** [comment]
@Havernis I dont get your idea, are you trying to **not overwrite** an previous download, and only write not existing files ? because that would be what I need, but shouldnt you then be checking if it is **not** a file ?

**Comment by Hummus-Ful** [comment]
@erdincay, As far as I can remember, the stream.py needs to return a file to the main function by either downloading it or, as mentioned above, return the already existing (path to) file.
I can see the developer has made some changes since the comment was posted, therefore I recommend you track the changes and verify the above is still answer your needs.
