### ISSUE TITLE
[Question?] How to change video name save ?

### ISSUE THREAD

**Issue by hangocanh2303** [pytube/pytube#380]
I want to change name of video when I save it, how can i do that ?

**Comment by Medstar117** [comment]
You answer lies [here](https://python-pytube.readthedocs.io/en/latest/api.html#pytube.Stream.download) in the pytube API. One of the download function’s optional parameters is as follows:

> filename (str or None) – (optional) Output filename (stem only) for writing media file. If one is not specified, the default filename is used.

“Stem only“ refers to just the name you want, not including the file extension (e.g. filename=“example”, **NOT** filename=“example.mp4”). If you are using the CLI rather than the Python IDLE, then there is currently no way to specify neither a name nor a download target for the video stream (although @nficano has made a TODO comment within the cli.py script for such a parameter).

For future reference (not trying to sound like a smartass, just trying to be helpful as to avoid future issues with other people), this is a question, not an issue. Issues are related to errors within the program or to code snippets no longer working as intended, and are to be posted in this section of the repository for people to be notified and, hopefully, for people to provide a solution. If you have a question, such as this, I would recommend posting it on sites such as [StackOverflow](https://www.stackoverflow.com/) rather than posting it here. Thank you~ :)

**Comment by harishbp** [comment]
yt.streams.first().download(output_path="path_to_dir", filename="filename")

**Comment by egemenayd** [comment]
Hi. I have a question. I want to name the videos by input. I tried to use inputs inside like ;   

```
"what would you like to do file name? "
input= name 

yt.download("D:/yt", name) 

```
(i know syntax is wrong but I tried to explain I hope I did..:)
