### ISSUE TITLE
Seems as if _extract_fmt is failing silently.

### ISSUE THREAD

**Issue by jonathanendersby** [pytube/pytube#47]
## Only seems to occur on some videos (like 2 out of 150 so far).

from pytube import YouTube
yt = YouTube()
yt.url = 'http://www.youtube.com/watch?v=y_0Snb1cnHY'

---

ox:xxxx jonathan$ python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    yt.url = 'http://www.youtube.com/watch?v=y_0Snb1cnHY'
  File "/Users/jonathan/Desktop/xxxx/pytube/api.py", line 95, in url
    self._get_video_info()
  File "/Users/jonathan/Desktop/xxxx/pytube/api.py", line 294, in _get_video_info
    self.videos.append(Video(url, self.filename, *_fmt_data))
TypeError: type object argument after *_ must be a mapping, not NoneType

**Comment by Andrej730** [comment]
Hello, have just the same issue with https://www.youtube.com/watch?v=nF32W_gSHnQ

```
Traceback (most recent call last):
  File "D:\test.py", line 11, in <module>
    yt.url = url
  File "C:\Python34\lib\site-packages\pytube-0.2.0-py3.4.egg\pytube\api.py", line 95, in url
  File "C:\Python34\lib\site-packages\pytube-0.2.0-py3.4.egg\pytube\api.py", line 293, in _get_video_info
TypeError: type object argument after ** must be a mapping, not NoneType
```

After some debugging with logs i found that this error happening cause _extract_fmt method from api.py (for some reason, i cant exactly tell why, cause i dont have get too much in all this encoding stuff) return None value for fmt_data and then _get_video_info method assign of this None to fmt_data:

``` python
fmt, fmt_data = self._extract_fmt(url)
```

And then this method trying to use None to unpack it as a dict with keyword arguments

``` python
self.videos.append(Video(url, self.filename, **fmt_data))
```

And error happening, cause there's no handling of this possible None. But  i have two fast solutions:

1) Add an if-statement before using fmt_data to check is fmt_data None or not.
Replace this in _get_video_info:

``` python
self.videos.append(Video(url, self.filename, **fmt_data))
self._fmt_values.append(fmt)
```

With this:

``` python
if fmt_data:
    self.videos.append(Video(url, self.filename, **fmt_data))
    self._fmt_values.append(fmt)
```

2) Also i found that after fmt_data assignment there is some TypeError catching. So, we can use it for other solution (that probably implied in code) - return in _extract_fmt just None instead of (itag, None).
Replace in _extract_fmt this:

``` python
if not attr:
    return itag, None
```

With this:

``` python
if not attr:
    return None
```

I hope it'll be helpfull.

**Comment by nficano** [comment]
@Andrej730 Thanks for your help! all patched.
