### ISSUE TITLE
Is there a way to get the video list of a channel?

### ISSUE THREAD

**Issue by bushnerd** [pytube/pytube#514]
I notice the Playlist function, but it seems the lib do not provide the way to get the video list with a given channel id or link.
Could you please the add the feature?

**Comment by braindotai** [comment]
Unfortunately, developers of pytube don't seem to be bothered by issues we create... The last closed issue was over a month ago... so I ain't think this issue is gonna resolved sooner or later. 
So I created my own simple version of web scrapping through which you can extract all the urls of all videos in a playlist.
```python
def playlist(url):
	source = requests.get(url).text
	soup = BeautifulSoup(source, "lxml")


	container = soup.find("div", class_ ="playlist-videos-container yt-scrollbar-dark yt-scrollbar")
	playlist = container.find("ol", class_="playlist-videos-list yt-uix-scroller yt-viewport")

	# titles = [title(string) for string in playlist.find_all("h4", class_ = "yt-ui-ellipsis yt-ui-ellipsis-2")]
	urls = ["https://www.youtube.com/" + video.prettify().split('"')[5] for video in playlist.find_all("a")]
	return urls
```
Just copy the url of any video in the playlist and pass it as the argument, it will return the list of all the urls.

Hope this helps
P.S. You need to install beautifullsoup4, requests and lxml to use this, simply install them using pip.

**Comment by moviedatascience** [comment]
You can go to the channel tab and click play all to create a playlist of all the videos for a channel. 

It won't give you a text list of all the videos, but it will give you a playlist.

**Comment by bushnerd** [comment]
ok, i see. Thanks for your reply. I have use another method.

**Comment by akraus53** [comment]
> ok, i see. Thanks for your reply. I have use another method.

Well then tell us!!

**Comment by Camelaoon** [comment]
Yes why don't u tell us?

**Comment by alebychac** [comment]
another way passing the url of the playlist:
`def get_playlist_video_tiltles(url):
        source = requests.get(url).content
        soup = BeautifulSoup(source, "lxml")
        script = [s for s in soup.find_all("script") if "var ytInitialData" in str(s)][0].text
        ytInitialData = loads(script.split("ytInitialData = ")[1][:-1])["contents"]["twoColumnBrowseResultsRenderer"]["tabs"][0]["tabRenderer"]["content"]["sectionListRenderer"]["contents"][0]["itemSectionRenderer"]["contents"][0]["playlistVideoListRenderer"]["contents"]
        titles = [v["playlistVideoRenderer"]["title"]["runs"][0]["text"] for v in ytInitialData]
        return titles``
