### ISSUE TITLE
Some streams not working (FORMAT_STREAM_TYPE_OTF)

### ISSUE THREAD

**Issue by swiftyy-mage** [pytube/pytube#543]
I noticed that on some videos, some of the streams don't work, they give a 404 error. Try this code to see:
    
    from pytube import YouTube

    yt = YouTube('https://www.youtube.com/watch?v=gaayOOnxiOU')
    yt.streams.get_by_itag(248).download()

I don't know why, I think I would have to learn JS to figure it out. I found that in

    self.player_config_args['player_response']['streamingData']['adaptiveFormats']

for the streams which do not work, there is always a key `'type'` which maps to a value `'FORMAT_STREAM_TYPE_OTF`. 
Also, for all these streams, in their counterpart in `self.player_config_args['adaptive_fmts']` there is always a key `clen`. In the videos which work, `clen` maps to a large integer, otherwise it maps to `'0'`. As a temporary measure in the method `initialize_stream_objects` in `__main__.py` I changed 

    self.fmt_streams.append(video)
to

    if (not stream.get('clen')) or int(stream['clen']):
        self.fmt_streams.append(video)
because although this doesn't actually make those videos downloadable, it does at least remove them from the streams list so anyone using this library for various things will not have to worry about this issue.

**Comment by movraxrsp** [comment]
After a quick look around, I saw nothing helpful, only that it is a known issue at least since last January.

[youtube-dl](https://github.com/ytdl-org/youtube-dl) [committed a change last January to drop FORMAT_STREAM_TYPE_OTF as unsupported, see here.](https://github.com/ytdl-org/youtube-dl/blob/484637a9ccede2967a709d2026d29d7b61560e43/youtube_dl/extractor/youtube.py#L1986).

[They had a little discussion here too.](https://github.com/ytdl-org/youtube-dl/issues/18804)

**Comment by hbmartin** [comment]
Is this still an issue with pytube3?
