### ISSUE TITLE
KeyError:None exception with order_by('resolution')

### ISSUE THREAD

**Issue by MaxLevs** [pytube/pytube#550]
I tried to execute this:
```py
yt = YouTube('https://www.youtube.com/watch?v=9QpzQN29EoY')
yt_streams = yt.streams\
    .filter(file_extension='mp4')\
    .order_by('resolution')
```

A `yt_streams.all()` is should be contains something like this:
```py
[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028">,
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">,
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f">,
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">,
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015">,
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c">,
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2">]
```

In fact order_by('resolution') raised KeyError:
```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/Users/maxlevs/PycharmProjects/youtube_downloader_tele/venv/lib/python3.7/site-packages/pytube/query.py", line 183, in order_by
    key=key,
  File "/Users/maxlevs/PycharmProjects/youtube_downloader_tele/venv/lib/python3.7/site-packages/pytube/query.py", line 176, in key
    return integer_attr_repr[getattr(s, attribute_name)]
KeyError: None
```

**Comment by swiftyy-mage** [comment]
Thanks for posting this problem, I think I have found a solution.
In `__main__.py`, change the method `initialize_stream_objects` so that 

    self.fmt_streams.append(video)
becomes

    if (not stream.get('clen') or int(stream['clen'])) and (video.includes_audio_track or not video.resolution == None):
        self.fmt_streams.append(video)
.
I have previously had similar issues with certain streams which pytube in it's current form cannot download still appearing in the streams list. I could not figure out how to download them so made a fix to remove them from the streams list, see #543. This is a little different, the streams with resolution `None` download fine but they won't play on my Media player, it tells me I needed the x-gst-fourcc-av01 decoder. I think for the mean time it is best if we remove these streams from the stream list.

However, even with this fix, your code still won't work. You need to change it to 

    yt_streams = yt.streams\
        .filter(custom_filter_functions=[lambda s: s.includes_video_track], \
        file_extension='mp4')\
        .order_by('resolution')\
        .all()

or anything else which gets rid of the audio only tracks, because you are trying to order by resolution when the audio tracks do not have a resolution.
I will test this a little bit more before I submit a pull request, but it should work for you.

**Comment by movraxrsp** [comment]
For the OP's problem, I recommend against modifying ``initialize_stream_objects()`` in ``__main__``.

The real problem is in ``query.py`` in the method ``order_by()``.

[I've made a commit on my fork that fixes the OP's problem and a more general problem in ``query.py``.](https://github.com/movraxrsp/pytube/blob/72b2da4bf6bbd6856609bfc05982c4588a207310/pytube/query.py#L159)


In ``query.py``, you can replace lines 165 to 171 with this:
```
        fmt_streams = []
        integer_attr_repr = {}
        for stream in self.fmt_streams:
            attr = getattr(stream, attribute_name)
            if attr:
                fmt_streams.append(stream)
                num = ''.join(x for x in attr if x.isdigit())
                integer_attr_repr[attr] = int(''.join(num)) if num else None
        self.fmt_streams = fmt_streams
```

After doing that, here's some test code with the OP's URL

```
from pytube import YouTube

mp4s = YouTube('https://www.youtube.com/watch?v=9QpzQN29EoY').streams.filter(file_extension='mp4')

print('\nall:')
for i in mp4s.all():print(i)

print('\nresolution order:')
for i in mp4s.order_by('resolution').all():print(i)
```

and its output

```
all:
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028">
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015">
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c">
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2">

resolution order:
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c">
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015">
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028">
```

**Comment by hbmartin** [comment]
@MaxLevs  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
