### ISSUE TITLE
Error in steam: Dict

### ISSUE THREAD

**Issue by vardhannegi** [pytube/pytube#575]
you guys messed up the entire pytube my old codes are not running any more there is a common error showing in the streams.py

**Comment by hbmartin** [comment]
This isn't a useful comment. It's better to provide details of a problem than just criticize.

**Comment by vardhannegi** [comment]
sorry for the previous comment. I saying that now pytube is not running even this simple code
`from pytube import YouTube
yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')
k = yt.streams
print(k)`
even for the other code it's showing the same error which is

> File "/home/iiser/Desktop/ml/youtube_downloader-master/pytube/streams.py", line 30
    def __init__(self, stream: Dict, player_config_args: Dict, monostate: Monostate):
                             ^
SyntaxError: invalid syntax

and sorry again. please accept my apologize

**Comment by palashgoel7** [comment]
I can't find this line in the current code-base. Did you make some changes to the code-base locally?
Also, please post your Python version

**Comment by swiftyy-mage** [comment]
This works fine for me using pytube3 (I used new lines though). On the other hand, a SyntaxError in `streams.py` would not be caused by the code you wrote using the library, it would be caused by whatever version of the library you have or how that library is running in your environment. `streams.py` is the first module imported in `__init__.py` and `Stream.__init__`  is the first method defined in `streams.py`. So I think that when your interpreter is running it's syntax check which it does before actually running any code, it gets to the first line which uses typing extensions and doesn't know what it is, causing a SyntaxError. Just a theory.

Make a fresh venv in Python 3.6 or above, run 

    pip install pytube3

and then try running your code using that. Let me know how it goes, I'll try and help get this fixed for you. Be more polite in the future. This is open source, and if we did make a mistake with this (doubt it) we will obviously fix it, but you didn't even tell us which python version or which pytube version you are running. You didn't even give us the code you were trying to run.

**Comment by vardhannegi** [comment]
I'm using python 3.7. It's now working properly after installing pytube3. Thanks for helping and for being kind and sorry to all contributor for my misbehave.

**Comment by swiftyy-mage** [comment]
It's cool don't worry dude.

**Comment by ErwinZhang88** [comment]
> I'm using python 3.7. It's now working properly after installing pytube3. Thanks for helping and for being kind and sorry to all contributor for my misbehave.

how to solve this. i am using python3.7 and pip3
