### ISSUE TITLE
AttributeError: 'YouTube' object has no attribute 'download'

### ISSUE THREAD

**Issue by vinosamari** [pytube/pytube#654]
Please help me understand what's going wrong.
I get the following error when i run this code:

import pytube
from pytube import YouTube

video_link = YouTube('https://www.youtube.com/watch?v=HZVG4itf9yw')
print('=====#####=====')
print(f'Downloading {video_link.title}')
print('=====#####=====')
video_link.download()
print('=====#####=====')
print('Done!')
print('=====#####=====')

Error:

VS-2:youvid_downloader user$ /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 "/Users/users/Documents/PYTHON DOCS/youvid_downloader/youvid_donwloader.py"
=====#####=====
Downloading Close Racquetball Serve
=====#####=====
Traceback (most recent call last):
  File "/Users/user/Documents/PYTHON DOCS/youvid_downloader/youvid_donwloader.py", line 8, in <module>
    video_link.download()
AttributeError: 'YouTube' object has no attribute 'download'

**Comment by SirSKillz** [comment]
The actual YouTube object does not have a download attribute. In order to download a video, you must access the streams and then download those.

You can check out the README, which has a quick start and explains it in plenty of detail: https://github.com/nficano/pytube/blob/master/README.md

If you just want the answer, all you need to do is:
`video_link.streams.get_highest_resolution().download()`

This will get the highest resolution video and download that. If you'd like to play around with it more (like getting different qualities, audio only, etc.) check out the rest of the README or https://python-pytube.readthedocs.io/en/latest/

Good luck!

**Comment by vinosamari** [comment]
> The actual YouTube object does not have a download attribute. In order to download a video, you must access the streams and then download those.
> 
> You can check out the README, which has a quick start and explains it in plenty of detail: https://github.com/nficano/pytube/blob/master/README.md
> 
> If you just want the answer, all you need to do is:
> `video_link.streams.get_highest_resolution().download()`
> 
> This will get the highest resolution video and download that. If you'd like to play around with it more (like getting different qualities, audio only, etc.) check out the rest of the README or https://python-pytube.readthedocs.io/en/latest/
> 
> Good luck!

Thanks for the response. Clarified the bugs. so because i didn't request for the streams i was calling the wrong function/method in the wrong place then?
