### ISSUE TITLE
Playlist can't get more than 100 videos

### ISSUE THREAD

**Issue by eddiewng** [pytube/pytube#684]
Hi, 
I am trying to download a playlist with more than 100 videos, but can only get 100 urls.
I think the problem may occur from playlist.py's `def _find_load_more_url(req: str)`, may google change something so the function failed. However i am not familiar it.
Can someone give a advice?
Thx

**Comment by RONNCC** [comment]
@eddiewng  can you provide a small code sample showing the problem /w the error log 

https://github.com/nficano/pytube/blob/master/Contributing.md#did-you-find-a-bug

**Comment by tooxo** [comment]
The bug is caused by YouTube changing their website layout for playlists. The videos are only loaded in using js from a json placed on the site. 

Example
```
window["ytInitialData"] = { ... json ... }
```

Inside this json details about the videos shown on the page as well as the continuations can be found.
To fix this issue, a rework of _extract_videos() and _find_load_more_url() is required.
I think I will open a PR in the next days and will update here.

Already reworked the _extract_videos function, so you could get an idea of what I am talking about.

```    
def _extract_videos(self, html: str) -> Tuple[List[Tuple[str, str]], str]:
        """
        @returns: List[str] url endpoints
        """
        initial_data_raw = self._js_regex.search(html).group(1)[0:-1]
        initial_data = json.loads(initial_data_raw)
        important_content = \
            initial_data["contents"]["twoColumnBrowseResultsRenderer"]["tabs"][
                0][
                "tabRenderer"]["content"]["sectionListRenderer"]["contents"][0][
                "itemSectionRenderer"]["contents"][0][
                "playlistVideoListRenderer"]
        videos = important_content["contents"]

        return uniqueify(
            list(
                map(
                    lambda x: f"/watch?id={x['playlistVideoRenderer']['videoId']}",
                    videos
                )
            )
        )
```

Sample json can be found [here](https://pastebin.com/YsJyZa5q)
