### ISSUE TITLE
pytube.YouTube(...) title attribute has missing charecters

### ISSUE THREAD

**Issue by kadir014** [pytube/pytube#741]
Whenever I try to get a video with `pytube.YouTube()` the title attribute always has missing characters in the beginning

I've tried
- `pytube.YouTube().title`
- `pytube.YouTube().streams[0].title`
- `pytube.YouTube().streams[0].default_file`
but none of them worked, there always is a missing chunk in the beginning of title

**Comment by tfdahlin** [comment]
@kadir014 are you still having this problem? If so, can you give me an example of a video that this isn't working correctly on?

**Comment by tfdahlin** [comment]
I'm going to close this issue, since it's been 2 weeks without a response. If you reinstall pytube with `python -m pip install git+https://github.com/nficano/pytube` and still have this problem, feel free to open a new issue, but please provide more details about how you're using pytube so we can try to figure out the problem
