### ISSUE TITLE
ImportError: cannot import name urlencode on python2

### ISSUE THREAD

**Issue by cumulus13** [pytube/pytube#756]
where is "urlencode" method/function/class ?:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sdk/anaconda2/lib/python2.7/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/sdk/anaconda2/lib/python2.7/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/sdk/anaconda2/lib/python2.7/site-packages/pytube/extract.py", line 8, in <module>
    from pytube.compat import urlencode
ImportError: cannot import name urlencode

**Comment by RONNCC** [comment]
@tfdahlin  any idea?

**Comment by tfdahlin** [comment]
This is actually an issue that's carried over from hbmartin's code getting merged into this repository -- hbmartin explicitly [dropped support for python2](https://github.com/nficano/pytube/commit/fcd83e156701fdc7fcb71d841792c04804f2e0bb#diff-587b5cc69beab67af9928d61a9987cc9116f317f308120ac5ef1cd28f61173ea) (which i think is reasonable, considering python2 is EOL as of the beginning of this year). When this happened, hbmartin removed the `pytube/compat.py` file. I think somewhere along the line, the pypi version got updated in a weird way, so there are still references to a missing file when you `pip install` pytube. 

I actually meant to open an issue to ask for your input on whether we should continue down the path of dropping support for python2 going forward, since I realized that was going to be a problem while I was working on the documentation updates, as well as what the process looked like for updating the pypi package. Part of my original motivation to contribute to this was a similar issue when attempting to install with `pip` locally.

cc: @RONNCC

**Comment by tfdahlin** [comment]
In the meantime, @cumulus13 you might have some luck if you use `pip install pytube==9.5.3` to install the last version before hbmartin's changes. I seem to recall some breaking changes to the youtube interface that prompted the updates that hbmartin worked on, however, so I don't know if that will even work. 

I would heartily recommend updating your code to python3 if you're able to since python2 is end-of-life, then cloning the repository and installing it from source. To install from the repository, just clone the repo (with `git clone https://github.com/nficano/pytube`), then navigate to the directory it's installed in, and type `pip install .`.

**Comment by RONNCC** [comment]
@nficano thoughts on dropping python2?

**Comment by LiamColeman** [comment]
> @nficano thoughts on dropping python2?

I'd like to keep python2 support since jython doesn't support python3 yet.

**Comment by RONNCC** [comment]
@LiamColeman it seems unclear if the current main supports python2.
Could you help to test this - we would also have to rewrite part of @hbmartin's migration to use python2+3 compatible code fills

**Comment by LiamColeman** [comment]
> @LiamColeman it seems unclear if the current main supports python2.
> Could you help to test this - we would also have to rewrite part of @hbmartin's migration to use python2+3 compatible code fills

I changed my tactics and I am now using python3.8 with tk as the GUI.

**Comment by RONNCC** [comment]
@LiamColeman  so to clarify, you don't need python2 support anymore? 😄

**Comment by LiamColeman** [comment]
> @LiamColeman so to clarify, you don't need python2 support anymore? 😄

Sorry for the late reply. Yep. I don't need it anymore.

**Comment by tfdahlin** [comment]
I'm closing this issue, as python2 support has been dropped
