### ISSUE TITLE
Enable crowdsourced video caption creation

### ISSUE THREAD

**Issue by jmbowman** [pytube/pytube#82]
Having captions for all the videos would improve both the searchability and the accessibility of the site.  Doing it all at once would be a huge project, but encouraging site users to submit captions could make it possible to gradually get them all done.  MIT has a [captioning resources page](https://ux.mit.edu/accessibility/captions) that looks pretty useful.  It mentions [Amara](http://www.amara.org/en/), which is in use on pyvideo (but seems to have some [issues](https://github.com/pyvideo/richard/issues/284), at least as currently implemented).

We should at least make sure we allow usage of whatever Amara and YouTube captions and/or PyCon US live captioning already exists.

**Comment by logston** [comment]
@jmbowman Since we simply play the embedded version of the youtube videos (which comes with whatever captioning is already associated with the video there), should we move this issue to the pytube/data repo and point people at the youtube docs for adding captions?

https://support.google.com/youtube/answer/2734796?hl=en

**Comment by logston** [comment]
Closing in favor of https://github.com/pyvideo/pyvideo/issues/4
