### ISSUE TITLE
Mp3 Audio

### ISSUE THREAD

**Issue by DeepakChakravarthy** [pytube/pytube#831]
**Currently Audio-only Streams are**
-  Mp4 & Webm

Shall we Add Mp3 

@tfdahlin
@RONNCC 
😊

**Comment by tfdahlin** [comment]
Hi @DeepakChakravarthy, the reason that the audio-only streams are mp4 and webm is because that's how YouTube sends the files. Pytube doesn't do any processing on the output files because of the fact that doing so would require additional dependencies to function, such as ffmpeg. I think the process of converting output should probably be left up to the user so that they can use their preferred audio processing library, and to avoid adding 3rd-party dependencies to pytube.

**Comment by RONNCC** [comment]
@DeepakChakravarthy That said we would love additional contributions to the Pytube library if there's any core Youtube-related functionality missing :)
