### ISSUE TITLE
Zip all playlist videos.

### ISSUE THREAD

**Issue by RamkumarMrj** [pytube/pytube#832]
I have an idea to enhance the playlist which is of zipping all the playlist video into an one zip file, which will be easier for usage. 
I think this maybe the alluring feature of pytube - YouTube Space.🌍
😇

**Comment by tfdahlin** [comment]
hi @RamkumarMrj somebody in the past actually created a pull request for this, and I'm not sure if this is the best idea for pytube. As I mentioned in [this comment](https://github.com/nficano/pytube/pull/750#issuecomment-722482231), I believe a better course of action would be to allow the user to compress the files however they choose, because different users may want to use zip, gzip, bzip, tar, etc. My solution at the time was to return a list of filepaths where the videos were saved, but the playlist functionality has actually been changed significantly in [this PR](https://github.com/nficano/pytube/pull/819). Playlists no longer have a `download_all()` function, and instead users are expected to iterate over `Playlist.videos` to save them, so I don't think this feature is relevant as of version 10.0.0

**Comment by vinay-khatri** [comment]
dont zip youtube playlist videos. This indian rat has no idea what crap he is is talking about

**Comment by tfdahlin** [comment]
@vinay-khatri there's no need to be hostile.

**Comment by vinay-khatri** [comment]
he is the type of guy who use coding to sell fake followers on instagram
