### ISSUE TITLE
pytube not working (KeyError: 'assets' ) even when i run the gui version still the same issue.

### ISSUE THREAD

**Issue by MusheAbdulHakim** [pytube/pytube#834]
**After running the  two lines of code from the quickstart ** 
`>>> from pytube import YouTube    >>> YouTube('https://youtube.com/watch?v=2lAe1cqCOXo').streams.first().download()`

**This is a screenshot of the error i get :**
![Screenshot at 2020-11-20 21-09-43](https://user-images.githubusercontent.com/58814410/99850161-c8343f00-2b74-11eb-8930-46222605afcd.png)

**Comment by tfdahlin** [comment]
hi @MusheAbdulHakim this is because you don't have the correct version of pytube installed. I suspect somebody told you to install pytube3 or pytubex, which is why you're having this problem. Try running these commands:

`python3 -m pip uninstall pytube pytubex pytube3` to uninstall all versions of pytube
`python3 -m pip install pytube` to install the most recent version of pytube

**Comment by MusheAbdulHakim** [comment]
Thank you very much for your assistance. I tried pytube first and it was not working well so i had to explore the other ones.
But the problem has been resolved thanks
