### ISSUE TITLE
Broken video file

### ISSUE THREAD

**Issue by tslyf** [pytube/pytube#839]
Why if you get a link to an mp4 file in this way:
`pytube.YouTube("https://youtu.be/QkBgx06CIYE").streams.filter(type="video", mime_type="video/mp4",progressive=True).order_by("resolution").desc()[0].url`
then some videos on this link lead to a broken file. For example, this video clip: https://youtu.be/QkBgx06CIYE

When I click on the received link I see this:
![Скриншот 22-11-2020 125828](https://user-images.githubusercontent.com/52909030/99900790-e019d900-2cc2-11eb-91ee-3afc85d9b98a.png)

**Comment by tfdahlin** [comment]
hi @setaz213, I think the problem you're encountering has to do with YouTubes media distribution servers. If you run the same code a few times in a row, but spaced out by a few minutes, you'll probably see the subdomain change after a while. I believe this has to do with technical solutions for load balancing on YouTube's end, where they will serve the same video from different servers at different times, so trying to access a video on a server that no longer hosts that video may not work correctly after the file is no longer available there.

Can I ask what your use case is where you need to access the media stream url in this way, instead of simply using the `.download()` function on a stream to save the file?

**Comment by tslyf** [comment]
@tfdahlin,
> hi @setaz213, I think the problem you're encountering has to do with YouTubes media distribution servers. If you run the same code a few times in a row, but spaced out by a few minutes, you'll probably see the subdomain change after a while. I believe this has to do with technical solutions for load balancing on YouTube's end, where they will serve the same video from different servers at different times, so trying to access a video on a server that no longer hosts that video may not work correctly after the file is no longer available there.

There is no way to get a stream url this video of this itag?

> Can I ask what your use case is where you need to access the media stream url in this way, instead of simply using the `.download()` function on a stream to save the file?

¯\\_(ツ)_/¯ What's the difference? `.download()` also does not load this video with this itag

**Comment by tfdahlin** [comment]
Oh, actually, looking at this a little further, I think this is related to something else. Earlier when I ran the same code, I had no problems accessing the url it gave me, but now i'm consistently getting a 503 error for that specific stream (but not others). I think this problem is on YouTube's side, as other streams are working fine for me.

Do you run into the same issue if you don't sort by descending? i.e. does `pytube.YouTube("https://youtu.be/QkBgx06CIYE").streams.filter(type="video", mime_type="video/mp4",progressive=True).order_by("resolution")[0].download()` work?

**Comment by tslyf** [comment]
@tfdahlin 
This problem is with this itag (22, with other itags this is not observed) and with some videos. For some videos, it helps to wait and try again, for some, nothing helps.

Yes, most likely this is a YouTube problem

**Comment by tfdahlin** [comment]
Sorry I can't help with this more :/ I seem to recall seeing an issue in the past where YouTube advertises a video quality that it doesn't actually have, which may be related, but I can't seem to find the issue any more

**Comment by tfdahlin** [comment]
Since this seems to be an intermittent problem with YouTube itself and not pytube, I'm going to close this issue
