### ISSUE TITLE
Question: example for multiple calls over longer time

### ISSUE THREAD

**Issue by KoljaWindeler** [pytube/pytube#841]
Hi, I'd like to reuse this project in a Mediaplayer. 
So over the time it'll have to decrypt a lot of videoid to stream urls.

Is there any example that divides one-time needed calls, like loading the decrypt algorithm from the per-video part, where the decryption takes place? 

Thanks a lot!!

**Comment by tfdahlin** [comment]
hi @KoljaWindeler, I think what you're looking for is the `defer_prefetch_init` variable when creating YouTube objects. This would look something like this in your code:

```python
from pytube import YouTube

my_urls = [
    <youtube urls here>
]

for url in my_urls:
    yt = YouTube(url, defer_prefetch_init=True)
    do_stuff()
    do_more_stuff()
    do_even_more_stuff()
    # *now* we use the youtube object
    yt.prefetch()  # downloads all of the necessary HTML
    yt.descramble()  # builds the stream objects
```

Normally, you'll want to call `prefetch()` and `descramble()` consecutively (or at least very close to each other) because stream urls do expire, and these URLs are extracted from the html that is fetched in `prefetch()`.

**Comment by KoljaWindeler** [comment]
Hi and thanks for your response.
Yes that would certainly work. But wouldn't this download e.g. the player JavaScript multiple times? 
As of now it takes a couple of seconds to prefetch and descramble and I was wondering if it would be possible to speed things up by avoiding repeatedly doing certain things.

More like
```
Youtube.preload()
Wait until user hits play
Play(Youtube.descramble(url1).url)
Wait until track 1 ended
play(Youtube.descramble(url2).url)
```

Those calls would naturally be spread of a track length ..

**Comment by tfdahlin** [comment]
Ah, I understand. There isn't *currently* a clean way to do this, but you can perform a workaround that will prevent the library from making extra calls to fetch the javascript player specifically. To do this, you would do something like the following:

```python
from pytube import YouTube

my_urls = [
    <youtube urls here>
]

first_vid = YouTube(my_urls[0])
player_js = first_vid.js

for url in my_urls[1:]:
    yt = YouTube(url, defer_prefetch_init=True)
    yt.js = player_js
    yt.prefetch()
    yt.descramble()
```

I'll actually see if I can find a way to cache this as part of the library, you're absolutely right that we don't need to be redownloading the player javascript every time.

**Comment by tfdahlin** [comment]
I'm going to need to look into it a little bit, but we may actually be able to get rid of some of the other network calls.

**Comment by KoljaWindeler** [comment]
Sounds great and yes, that's exactly what I meant. I guess that will boost the performance quite a bit at the second call. Maybe you can even keep the object alive and only have some sort of "update_id()" method? Thanks

**Comment by KoljaWindeler** [comment]
Sorry didn't mean to close this

**Comment by tfdahlin** [comment]
I'm working on a method of caching the media player javascript at a module level [over in this branch](https://github.com/tfdahlin/pytube/tree/improvement/reduce_network_calls) that will hopefully boost performance. I don't think having an `update_id()` method really makes sense considering the entire object would need to be reinitialized, but it's almost certainly possible to cache at least the one network call for improved performance. Currently hitting a 403 error in my test suite of videos and need to go take care of something, but I'll try to have that fixed in a few hours, and hopefully have a PR in for this sometime today.

**Comment by tfdahlin** [comment]
Nevermind, I was dumb and just forgot to reinstall the library after making a change. I think the changes are working fine, and I've made a [PR](https://github.com/nficano/pytube/pull/842) if you want to take a peek.

**Comment by tfdahlin** [comment]
@KoljaWindeler the update that caches the media player js is now merged if you want to try it out, you'll just have to install from source:
`python -m pip install git+https://github.com/nficano/pytube`

**Comment by KoljaWindeler** [comment]
Thanks, already tried. Works great!
