### ISSUE TITLE
Apply the appropriate extension to the downloaded file

### ISSUE THREAD

**Issue by maneletorres** [pytube/pytube#847]
Goodnight.

I was wondering if there is any way to convert a YouTube video to '.mp3' format and have the generated file name use the appropriate extension. That is, using this piece of code:

`filePath = yt.streams.filter(only_audio = True).first().download(folderName)`

I download the YouTube video in '.mp3' format but continue to use the source extension '.mp4'. Although its content and size are correct, I would like to know if the library includes any option to also transform the file name to the extension '.mp3'.

I have applied the following line of code to correct it, but if there is an option using your library it would save me this part of code:

`os.rename(filePath, folderName + yt.title + ".mp3")`

Thank you very much in advance and sorry for the inconvenience.

PS: this is my first contribution to a GitHub repository.

**Comment by xenonstride** [comment]
Hello,
`os.rename(filePath, folderName + yt.title + ".mp3")`
You cannot convert an mp4 file to mp3 using os.rename because it is just renaming the file but not converting it. (check this : https://superuser.com/questions/862874/saving-mp4-audio-file-as-an-mp3-file)
Pytube doesnt have a function for converting the downloaded files, so this is not an issue of pytube.
You should use the python module `ffmpeg` for conversion of files from one format to another.

**Comment by tfdahlin** [comment]
hi @maneletorres, @xenonstride is correct. The extensions that pytube applies to the files it produces are correct -- youtube does not transmit its streams in the .mp3 format, and simply changing the file extension does not convert these files. This is also not something that pytube can change, so we would recommend using another service, like `ffmpeg`, to accomplish this.
