### ISSUE TITLE
NameError: name 'RegexMatchError' is not defined (installed pytube from Master)

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#859]
I work on spotDL/spotify-downloader and [this is a common issue we run across](https://github.com/spotDL/spotify-downloader/pull/994#issuecomment-739042164).

It occurs only for some users under different circumstances, e.g.
- pytube works just fine from a fork of pytube I uploaded to PyPi called `a-pytube-fork-for-spotdl-users`. It also doesn't work for some of the users on our stable branch. It works for most of them.
-  It doesn't work on the PR in question (see link). again among the 4 testers, it works for 2 doesn't for the other 2.

We (the dev team) would like some help with this and the other pytube issues.

---------------------------------
Just a side note:
- Consider rewriting the whole of pytube from scratch. It usually reduces package size drastically.
- Definitely more reliable.
- If you write it with maintainability in mind - it'll have a much simpler design, that's a bonus for attracting more contributors. 
- Most of the trial and error is already done, you just have to restructure it for all of those benefits.

Now, I'm sure there are reasons you aren't doing this but just wanted to share by 2 cents with you. It got the project that I 'inherited' form [this muck](https://github.com/spotDL/spotify-downloader/tree/5873f8ff8a37d96ab257b420b8ff88372d801a3b) into a [maintainable state](https://github.com/spotDL/spotify-downloader) with much better search capabilities.

**Comment by tfdahlin** [comment]
hi @Mikhail-Zex 

Just going to go through a few things here.

That issue you're running into is actually coming from your patch code in spotDL and not pytube itself -- I looked through the traceback as well as your codebase, and its failing on [this line](https://github.com/spotDL/spotify-downloader/blob/master/spotdl/patches/pyTube.py#L241).

The problem here is that you're raising RegexMatchError, which is a custom pytube exception, without actually importing it in your patch file. The quick solution to your problem would simply be to add `from pytube.exceptions import RegexMatchError` [here](https://github.com/nficano/pytube/issues/769#issuecomment-717576449). 

However, this isn't a robust solution.

What I would recommend to you is to drop [this file](https://github.com/spotDL/spotify-downloader/blob/master/spotdl/patches/pyTube.py) altogether. My guess is that the file was initially created because of the fact that the pytube repo was unmaintained for a period of time, and spotDL was trying to work around this by manually patching the YouTube objects. In fact, in the version you linked before you started restructuring the project, I can see that the [equivalent file](https://github.com/spotDL/spotify-downloader/blob/5873f8ff8a37d96ab257b420b8ff88372d801a3b/spotdl/patch/youtube.py) to `pyTube.py` also didn't import the custom exception, but still raised it. If you do this, it will be *vastly* easier for me to provide support to your project, and it will improve the reliability of pytube overall. I try to check this repository on a regular basis (usually daily if I have the time) to make sure that issues and pull requests get responded to in a reasonable amount of time, and would be happy to resolve issues that stem directly from the pytube codebase. That's a lot more challenging for me to do when the problem could be coming from a weird patch file like it is currently.

I only started earnestly contributing to pytube a month and a half ago, and became a maintainer of pytube a month ago, but I have been steadily working towards improving the codebase and making sure that issues get resolved. If you have specific issues stemming from pytube itself, I'm 100% happy to try and resolve them as they come up.

**Comment by ghost** [comment]
Don't get me wrong. I've been the admin on spotdl for only a month. What I said above were just things that helped me get spotdl into a maintainable state. Just my 2 cents.

 I really appreciate the work you've done on pytube. Thought I should share a boot of what helped me.

As to the error, I'll get to you by tmrw.

**Comment by aklajnert** [comment]
I think the patch doesn't affect the behavior too much, but I think that the `spotify-downloader` uses the wrong dependency - `pytube3` instead of `pytube`.

Consider the following example:  
```python
from pytube import YouTube

yt = YouTube("https://youtu.be/dQw4w9WgXcQ")

print("Instantiated")
```

With `pytube3`:  
```python
Traceback (most recent call last):
  File "scratch.py", line 3, in <module>
    yt = YouTube('https://youtu.be/dQw4w9WgXcQ')
  File "/tmp/pytube/lib/python3.8/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/tmp/pytube/lib/python3.8/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/tmp/pytube/lib/python3.8/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "/tmp/pytube/lib/python3.8/site-packages/pytube/extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
```

With `pytube`, version `10.0.0`, the `YouTube` object gets instantiated correctly. The patch doesn't seem to be necessary anymore, but it doesn't seem to be the root cause of the problem.

**Comment by ghost** [comment]
I ran my tests with pytube not pytube 3. You need top import pytube regx errors too

**Comment by tfdahlin** [comment]
Since this issue is coming from a patch made to pytube in your library, I'm going to close it for now. If you have a problem with pytube itself in the future, please feel welcome to create a new issue.
