### ISSUE TITLE
Some videos return an empty StreamQuery list

### ISSUE THREAD

**Issue by x1001000** [pytube/pytube#868]
E.g.
`YouTube('https://youtu.be/wyx6JDQCslE').streams` returns `[]`

**Comment by tfdahlin** [comment]
hi @x1001000 I'm not running into this problem currently. Can you confirm your version of pytube for me by running `print(pytube.__version__)` please?

**Comment by x1001000** [comment]
@tfdahlin 10.0.0

**Comment by tfdahlin** [comment]
That's why. This problem was reported in https://github.com/nficano/pytube/issues/845, and fixed a few PR's ago. I would recommend installing the latest version of pytube directly from the source with `python -m pip install git+https://github.com/nficano/pytube`, which should fix this problem for you. I'm working on getting the most recent changes pushed to PyPI, but for the time being, installing from source should work to fix this problem for you.

**Comment by x1001000** [comment]
@tfdahlin You are awesome! Thank you.

**Comment by tfdahlin** [comment]
Glad that fixed it for you!
