### ISSUE TITLE
Urls of playlist not showing up

### ISSUE THREAD

**Issue by dw-liedji** [pytube/pytube#880]
The following code is just returning 1, instead of videos urls of the playlist

for url in p.video_urls[:3]:
    print(url)

**Comment by tfdahlin** [comment]
hi @l-i-e-d-j-i-6-7-8-w-d I believe you're using an old version of pytube, as this was fixed in a recent update. Please run the following:
```python
import pytube
print(pytube.__version__)
```
If this does not print `10.1.0`, then you have an old version. If you have an old version, please uninstall pytube, then reinstall it with the following command:
`python -m pip install git+https://github.com/nficano/pytube`

**Comment by rupindr** [comment]
@tfdahlin How can we make sure that v10.1.0 is installed by default when using `python -m pip install pytube`? If that is not possible, can we change the documentation to show `python -m pip install git+https://github.com/nficano/pytube` as the only install command? I'd be happy to raise a PR for that.

**Comment by tfdahlin** [comment]
@rupindr the reason that 10.1.0 is not installed with `python -m pip install pytube` is because `pip install` attempts to install from pypi by default. Pypi is maintained separately from github, and I don't have access to it to upload newer version of pytube currently. I already have a [pull request](https://github.com/nficano/pytube/pull/871) to automate this process, so that this won't be an issue any longer, I'm just waiting on the other maintainer to help me out with it. Once this process is automated, I'll be able to keep the normal `python -m pip install pytube` working, so changing the documentation would be superfluous.

**Comment by dw-liedji** [comment]
Thank you all of you for your comments. I have installed the  ```10.1.0``` version  using  ```python -m pip install git+https://github.com/nficano/pytube```  instead of ```pip install pytube``` and it works fine. However, you should upgrade the  ```PyPi``` version accordingly, because it still ```10.0.0```.
