### ISSUE TITLE
updating pytube to very last version ...

### ISSUE THREAD

**Issue by MonDieuJeTadore** [pytube/pytube#881]
**Using  ./python -m pip install git+https://github.com/nficano/pytube does not install the 10.3.0 version, but the 10.1.0 version. How to install the last version ?.**

![Snap6](https://user-images.githubusercontent.com/2625211/102521445-3b0dd880-4095-11eb-8333-a824dad57e0c.jpg)

**Comment by tfdahlin** [comment]
hi @Archanciel -- chances are you already have the latest version. The releases in the repository got slightly confused because of a mistake in our release system. Dependabot updated some dependencies, and tagged those updates, which caused new "releases" to be published. However, the version of pytube has not changed yet. I have a PR in to fix this, but as long as it says 10.1.0, you should be fine.

**Comment by tfdahlin** [comment]
I've removed the auto-generated releases and tags so that this is less confusing.
