### ISSUE TITLE
[BUG] pytube command-line utility silently fails if no options are passed

### ISSUE THREAD

**Issue by cottuli** [pytube/pytube#901]
You might not consider this to be a bug, but if you try to run something without any options like

`pytube https://www.youtube.com/playlist?list=PLcxPetO_cDzsFIiPRjvovY0Gfv1V7gBFu`

pytube outputs 

`Loading playlist...`

and then silently fails. 

I'd recommend either 

1. Use `youtube-dl`'s approach and by default make `pytube` try to download the audio and video files with the best available audio and video quality, or 
2. Warn the user that they need to provide an optional argument when `pytube` is called without specifying the --itag, -l, -a, or -f options.

In my particular case the default behaviour I expected was provided by using the -f option.

**Comment by tfdahlin** [comment]
hi @cottuli that's a great point, I'll look into making this more intuitive to use

**Comment by yvainyork** [comment]
I added a solution for that issue (s. #902 ) : I think that most people expect that pytube will try to download the best quality stream.

**Comment by tfdahlin** [comment]
I think it makes the most sense to go with option 2 here, and tell the user that at least one argument is required, rather than having a default behavior. The reason I think this makes the most sense is because pytube is written not to have any external dependencies. Defaulting to the `-f` flag introduces an external dependency by default. The highest quality videos can only be downloaded with adaptive streams (since progressive only goes up to 720p if I remember correctly), so we can't definitively say that it will default to the highest quality without introducing ffmpeg as a dependency for default behavior.

**Comment by yvainyork** [comment]
> I think it makes the most sense to go with option 2 here, and tell the user that at least one argument is required, rather than having a default behavior. The reason I think this makes the most sense is because pytube is written not to have any external dependencies. Defaulting to the `-f` flag introduces an external dependency by default. The highest quality videos can only be downloaded with adaptive streams (since progressive only goes up to 720p if I remember correctly), so we can't definitively say that it will default to the highest quality without introducing ffmpeg as a dependency for default behavior.

that's correct @tfdahlin  - I was considering to propose to allow ffmpeg as a dependency (I know that this also has issues - I am also a big fan of very little to no dependencies) but in this case the command line call via subprocess looks ugly to me, since ffmpeg has a nice python api. We could reduce the dependency issue by importing it only in the  _ffmpeg_downloader() function - still a little bit ugly, but less ugly than a subrocess call I would say :)  - coding is always a balance between different shades of ugliness ....

**Comment by yvainyork** [comment]
Although @tfdahlin made a good point about the dependency issue, I would also opt for option no. 1 (simply downloading the best progressive by default): this is the more intuitive and user friendly option. A user expects that the pytube command simply downloads a video by default and it should do it with as little command line options as possible (if one does not use pytube too often, one tends to forget these command-line options and how to really use it). What do you think about this @cottuli and @tfdahlin ?
-> KISS ;)

**Comment by maitreyee19** [comment]
I like @yvainyork suggestion

**Comment by tfdahlin** [comment]
This appears to be fixed, I believe due to the addition of default behavior for video downloads, so i'm going to close this issue
