### ISSUE TITLE
[Feature] : Using only links to free licensed, short videos (like CC) in examples/docs to reduce options of attack

### ISSUE THREAD

**Issue by yvainyork** [pytube/pytube#905]
**Is your feature request related to a problem? Please describe.**

I am a little concerned about these developments - and hope, that pytube does not experience a similar fate like
[youtube-dl ](https://en.wikinews.org/wiki/GitHub_blocks_public_access_to_youtube-dl_after_RIAA_issues_DMCA_notice)
and VideoDownloadhelper (Please go to http://www.downloadhelper.net/donate.php and click on the link "Why we do not use PayPal anymore" to get the full story about PayPal - very depressing.)

To reduce to options of accusation, I would propose to only use only links to free (e.g. videos with creative commons - CC- license) in all READMEs, examples and documentation. This at least could reduce the risk of accusing
 **pytube** to support downloads of copyrighted content (maybe).
I would also like to propose to use only short videos (max. 2 min length) in the examples to provide a fast result to the tester.

I know, it will only change a little, but might reduce options of attack.
- just an idea ....

**Comment by tfdahlin** [comment]
We actually took an initiative related to this a while back. Originally all of the documentation referred to the Gangnam Style video, and I went through and updated everything to point to a well-known video that could demonstrate the majority of the library's functionality. I settled on a YouTube Rewind video because of the fact that it had a lot of the relevant features (such as a lot of different quality levels, a wide collection of subtitle options, and more).

We could potentially make references to a creative commons-licensed videos, but it would need to support a lot of test cases for the library, which could prove challenging to find. I seem to recall a few weird test cases that prevented me from using certain videos, but I can't currently recall what they were.

Additionally, if the RIAA were to try to issue a takedown to this repository, regardless of what we use as our examples and test cases, they'll try to argue that we encourage users to violate copyright simply by existing, so I don't think we'll gain any protection by changing from using the examples we currently do.
