### ISSUE TITLE
Problem making pytube work in Spyder

### ISSUE THREAD

**Issue by DiegoGuisasola** [pytube/pytube#916]
I apologize beforehand if this is not the right place to write this.
I'm new in this world, just finished a course in Python and I'm trying to automatize some things.

I'm using a windows 10 pc. I've installed pytube via pip install pytube (installed the latest version) and it works great in cmd but when I want to write a script in Spyder, I get an error.

1. This is what is shown in cmd:

![image](https://user-images.githubusercontent.com/44145128/105572991-6afd6b00-5d28-11eb-9b70-29c8dce9eb7c.png)

2. This is shown in Spyder:

![image](https://user-images.githubusercontent.com/44145128/105572997-7a7cb400-5d28-11eb-868f-a2266e6b3af2.png)

3. At first, it wasn't working in cmd, I had to set some environmental variables: I think it looks a bit messy, any suggestion on how to improve this? I mean, in order not to add these paths for every single thing I install via pip

![image](https://user-images.githubusercontent.com/44145128/105573048-c9c2e480-5d28-11eb-97f1-a0bd5d70a923.png)

4. I added this path in Spyder with no luck:

![image](https://user-images.githubusercontent.com/44145128/105573095-32aa5c80-5d29-11eb-9ba5-7a5f9a54b151.png)

Any help would be very much appreciated.
Thanks in advance!

**Comment by tfdahlin** [comment]
hey @DiegoGuisasola this is definitely an issue with spyder and not pytube itself. 

To answer your question in (3.), you shouldn't need to edit the environment variables any more. Setting that is kind of a one-and-done deal, where any pip packages installed after this should just work. Basically all that does is provides your computer with a list of directories to look in for files. When you try to import something in python, it will basically look through the list of variables in your `PATH` for what it needs, and those are the only two places these things will get installed by pip. 

I suspect that the issue is that you haven't added `C:\Users\Elbox\AppData\Roaming\Python\Python37\Scripts` to the path in spyder. I'm not real sure why it wouldn't simply use your windows path stuff, but I also don't use spyder so I don't want to make any guesses. Try adding that extra path to your spyder pythonpath manager

**Comment by DiegoGuisasola** [comment]
Thanks for your recommendations!
Although I haven't been able to fix it, even with what you said. 
`Some modules are missing No module named 'pytube'`
Any ideas? :(

**Comment by tfdahlin** [comment]
Wait, actually, now that I look at it I'm seeing something else.

The python versions in your screenshots dont match:
![image](https://user-images.githubusercontent.com/9667869/105619779-dc3e2c00-5dc3-11eb-8445-8eba82640d20.png)
![image](https://user-images.githubusercontent.com/9667869/105619784-e6602a80-5dc3-11eb-94ee-ce33ca16162b.png)

Any idea why that might be? I suspect that this is probably related to your issue

**Comment by DiegoGuisasola** [comment]
Uhmmm, it might be because I installed Spyder first and conda, after that.

1. CMD installation directory: 
![image](https://user-images.githubusercontent.com/44145128/105620935-1ca3a700-5dd0-11eb-8117-897ec70ec18d.png)

2. In Spyder:
![image](https://user-images.githubusercontent.com/44145128/105620942-39d87580-5dd0-11eb-9941-77fd5f85d2a1.png)

Indeed, there are 2 different versions.
The problem is Idk which one should I uninstall or if I should uninstall everything and reinstall only conda. Any suggestions on this?

Thanks for your help!

Edit: I also have installed: Kotlin and Javascript.

**Comment by tfdahlin** [comment]
Ah, yeah, I suspected that might be the issue. Personally, my recommendation is always to use one of the standard python builds instead of conda. Any time I run into somebody who has conda installed, they have problems with a lot of standard python stuff. If you use one of the installers from python.org, there will be an option that's something like "set my PATH variables for me" that you'll need to select (its off by default), but at least you'll have more consistency that way.

Setting that aside, does spyder have its own console for installing pip packages? I assume you're using CMD separately, which might be causing the issues. if spyder does have its own console, you can try installing the package that way.

Additionally, are you running `pip install pytube`, or `python -m pip install pytube`? These will behave slightly differently, but the latter will provide more consistent results.

**Comment by DiegoGuisasola** [comment]
Spyder does have its own console and I've installed pytube through that console, still, Spyder doesn´t recognize it.

I used: pip install pytube

Should I just uninstall everything? And if so, how should I do it? Thank you su much for your help so far!

**Comment by tfdahlin** [comment]
Try adding `C:\Users\Elbox\AppData\Local\Programs\Spyder\Python` and `C:\Users\Elbox\AppData\Local\Programs\Spyder\Python\Scripts` to the spyder path manager, and see if that works. If it doesn't, I would recommend uninstalling everything, and starting from scratch.

Use Windows' "Add or remove programs" application to uninstall the relevant parts (looks like spyder, conda, and possibly visual studio's python extension?), then go to https://python.org to download and use an installer. When you run the installer, there should be an option to set the PATH variables for you. It's unchecked by default, so you will need to check it during the installation

**Comment by DiegoGuisasola** [comment]
I'm sorry for takin too long to response.
I'll uninstall everything and start from scratch.

Again, thank you so much for your help!

**Comment by tfdahlin** [comment]
No worries, good luck!
