### ISSUE TITLE
Getting this same issue!!!

### ISSUE THREAD

**Issue by Mastermind-sap** [pytube/pytube#921]
Getting this same issue!!!
```
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```
If anyone found a solution please help....probably we need a time lag in the download its too fast hence maybe it gets blocked. Any help?

_Originally posted by @Mastermind-sap in https://github.com/pytube/pytube/issues/757#issuecomment-769172353_

**Comment by tfdahlin** [comment]
hi @Mastermind-sap, are you downloading large numbers of videos really quickly? Or are you having issues with your connection? Issues like this are usually caused by either YouTube blocking your IP address, or an internet outage, both of which are outside of our control

**Comment by Mastermind-sap** [comment]
No my connection is totally fine.I was trying to download a playlist but the download stops at the first video. It downloads some part of the first video(every time it stops at different timestamp). I suppose youtube blocks it due to heavy streaming of packets. Is there anyway to add a time lapse in between the downloads or something.

**Comment by tfdahlin** [comment]
Unfortunately, that's not really possible. If you aren't using the CLI, you might be able to try something like this to make your code wait between video downloads:
```
import time
from pytube import playlist

p = playlist(playlist_url)
for url in p.video_urls:
    vid = YouTube(url)
    vid.streams.first().download()  # download the first stream
    time.sleep(20)  # sleep for 20 seconds between videos
```

**Comment by Mastermind-sap** [comment]
Yeah i did the same thing @tfdahlin 
But the download stops in between the first video so actually the time sleep is of no use.
Does downloading unlisted videos cause any error?(actually i am downloading some unlisted videos)

**Comment by Mastermind-sap** [comment]
any solution @tfdahlin ?

**Comment by tfdahlin** [comment]
hi @Mastermind-sap, sorry it's taken me so long to get to this. 

I'm going to need a little bit more information about this in order to try and help you fix it.
First, run the following and tell me what output you get:
```python
import pytube
print(pytube.__version__)
```
This should output 10.5.0 if you have it installed from the source, or 10.4.1 if you have it installed from pypi.

Second, run the following in your terminal:
```bash
python --version
```
This should output 3.6.0 or greater, as pytube is only tested for python 3.6+. 

How are you running this application you're using? For example, is this something you have hosted on a cloud server, or are you running it on your personal computer? You'll get different behavior, and this issue could be related to a firewall rule or something of that nature.

To answer your question about whether downloading unlisted videos causes errors, it depends on the video. An unlisted video that you can access with a link, but without needing to be logged in, should work just fine. You'll run into issues with private videos that need to be shared to your youtube account however. If you're iterating over a list, you should be able to use a try-catch block to capture this cases like this:
```python
for url in url_list:
    try:
        yt = YouTube(url)
    except VideoUnavailable:
        print(f'Video {url} is unavailable, skipping it for now.')
    else:
        print(f'Downloading {url}')
        yt.download()
```

**Comment by Mastermind-sap** [comment]
![image](https://user-images.githubusercontent.com/66560136/107848895-3fe4d380-6e1d-11eb-867f-4add64702a17.png)
![image](https://user-images.githubusercontent.com/66560136/107848910-5db23880-6e1d-11eb-9fa6-0e3150041928.png)
Here's everything you need! And I can access the video with just the link....specific user is not required. @tfdahlin

**Comment by tfdahlin** [comment]
Do me a favor and try this:
```python
import pytube.request

res1 = pytube.request.get('https://example.com')
res2 = pytube.request.get('https://youtube.com')
```

And show me the output

**Comment by Mastermind-sap** [comment]
![image](https://user-images.githubusercontent.com/66560136/108698359-0ea98900-752a-11eb-8422-03d962974b2c.png)
Here you go. @tfdahlin

**Comment by tfdahlin** [comment]
It's bizarre that those requests both work, but accessing a video doesn't. I don't know if I can really help with this at all, because I've never been able to reproduce this problem myself, so I can't even try to test fixes myself. Have you tried using a proxy when you download the videos?

**Comment by Mastermind-sap** [comment]
no i didnt use proxy @tfdahlin

**Comment by tfdahlin** [comment]
Try using a proxy and see if that fixes your problem. We really can't change the speed at which videos get downloaded individually

**Comment by Mastermind-sap** [comment]
ok thanks 👍 I will try
