### ISSUE TITLE
[BUG] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Felyppi** [pytube/pytube#937]
When running: 

from pytube import YouTube
YouTube('https://youtube.com/watch?v=2lAe1cqCOXo').streams.first().download()

Results in:
ValueError: not enough values to unpack (expected 2, got 1)

Python version: 3.9.1
Pytube version: 10.4.1

I user command:
pip install pytube

**Comment by vayuvegula** [comment]
Same. Tried 
1. Updating to Pytube3
2. Updated the regex in the cipher.py file in the site packages
3. Checked the extractor.py file for the code (fix 641?), but since I just downloaded pytube , looks like that fix was already on.
but getting the same error as below:

ValueError                                Traceback (most recent call last)
<ipython-input-36-a1df6ef554e0> in <module>
----> 1 yt = YouTube('https://www.youtube.com/watch?v=-tJYN-eG1zk')

~/Documents/anaconda3/envs/ProjectScrape/lib/python3.8/site-packages/pytube/__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
    103 
    104         """
--> 105         logger.info("init started")
    106 
    107         self.vid_info = dict(parse_qsl(self.vid_info_raw))

~/Documents/anaconda3/envs/ProjectScrape/lib/python3.8/site-packages/pytube/__main__.py in descramble(self)
    175             )
    176         else:
--> 177             self.vid_info_url = extract.video_info_url(
    178                 video_id=self.video_id, watch_url=self.watch_url
    179             )

~/Documents/anaconda3/envs/ProjectScrape/lib/python3.8/site-packages/pytube/extract.py in apply_signature(config_args, fmt, js)

~/Documents/anaconda3/envs/ProjectScrape/lib/python3.8/site-packages/pytube/cipher.py in __init__(self, js)
     34 
     35     def get_signature(self, ciphered_signature: str) -> str:
---> 36         """Decipher the signature.
     37 
     38         Taking the ciphered signature, applies the transform functions.

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by mvn-rvn** [comment]
I'm having the same issue. Thought it was something with the link I was using, but it's for every link.

**Comment by Neilsaw** [comment]
same.

This error found form 0:00 GMT 23/2/2021

**Comment by zhaowei0315** [comment]
Same Error
not enough values to unpack (expected 2, got 1)

**Comment by TimOgden** [comment]
I have the same issue, began a few hours ago, not exactly sure when.

I have python 3.9.1 and I pytube 10.5.0 installed through pip.

Tried `pip install --upgrade pytube` to make sure it was up-to-date and also:

```
pip uninstall pytube
pip install pytube3
````

and also:

```
pip uninstall pytube3
pip install git+https://github.com/nficano/pytube
```

and same error for all

**Comment by tfdahlin** [comment]
Sounds like something changed on YouTube's end. I don't think I can get a change for this in tonight, but I'll look into a fix.

**Comment by tfdahlin** [comment]
Should be fixed in the latest release
