### ISSUE TITLE
[BUG] ImportError: cannot import name urlencode

### ISSUE THREAD

**Issue by Trollport** [pytube/pytube#945]
I just installed the newes python and pytube, still pytube isn´t working at all.
I just started with python (i know c++ so i get the basics (i hope))
Am i just too bad using python?

**Describe the bug**
Using this in python cmd:
`pytube https://youtube.com/watch?v=2lAe1cqCOXo`
I get: SyntaxError: invalid syntax

using the same line on Linux i get:
ImportError: cannot import name urlencode

using this:
`from pytube import YouTube
yt = YouTube("https://youtu.be/U16Xg_rQZkA")
print(ty.title)
stream = yt.streams.first()
stream.download()`
nothing happends and cmd just closes

using this:
`from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=-TEGPelS3Ac').streams.first().download()`
the same happens

**System information**
Please provide the following information:
newest python version
newest pytube version
win 10/ Ubuntu

**Comment by tfdahlin** [comment]
hi @Trollport if you're getting `ImportError: cannot import name urlencode` then you're probably running python2, not python3. In the python cmd, run this to check:
```python
import sys
print(sys.version)
```

**Comment by Trollport** [comment]
true, using python 3.8.8 now and its back to syntax error:
`>>> pytube https://www.youtube.com/watch?v=U16Xg_rQZkA
  File "<stdin>", line 1
    pytube https://www.youtube.com/watch?v=U16Xg_rQZkA
                ^
SyntaxError: invalid syntax`

used both install commands given on https://pypi.org/project/pytube/

`>>> print(pytube.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pytube' is not defined`

**Comment by tfdahlin** [comment]
@Trollport the SyntaxError is because you're trying to run a shell command from the python interpreter. 

Open up windows powershell, run `python --version`, and tell me if that says version 2 or 3. My guess is that you haven't uninstalled python2, so it's trying to install pytube for python2, and not python3.

**Comment by Trollport** [comment]
python --version returns
Python 3.8.8

**Comment by Trollport** [comment]
> @Trollport the SyntaxError is because you're trying to run a shell command from the python interpreter.
so "pytube https://www.youtube.com/watch?v=U16Xg_rQZkA" belongs into normal win cmd?
because that doesn´t work aswell (unknown command)

**Comment by tfdahlin** [comment]
yes, `pytube https://www.youtube.com/watch?v=U16Xg_rQZkA` belongs in the normal win cmd, however it will require you to have your PATH set up correctly. When you installed python, did you use an installer from python.org? Part of their installation process asks you if you want to set the PATH variable, and if you didn't check that box, you'll need to set your PATH variable manually. It's kind of annoying to do that though, so you might try re-installing python and making sure to check that box during the installation

**Comment by tfdahlin** [comment]
I'm going to close this due to inactivity

**Comment by Trollport** [comment]
python path is setup (if i type "python" into cmd it starts python interpreter)

**Comment by tfdahlin** [comment]
it's a little more complicated than that, since python uses two path variables.
Check your windows environment variables to see if you have two entries for python, that should look something like this:
1. `C:\Users\<username>\AppData\Local\Programs\Python\Python38\Scripts`
2. `C:\Users\<username>\AppData\Local\Programs\Python\Python38\`
The `scripts` folder is used for command line python programs (like running `pytube <video_url>` in powershell), while the other one is for importing libraries in a script you've written.
The "unknown command" error you're getting is likely because you're missing the first PATH variable i listed above, while the syntax error might be from having a mistake in the second one (e.g. if you only have the PATH set up for python2 instead of python3)

**Comment by Trollport** [comment]
thank you! finally works :)
