### ISSUE TITLE
Why pytube can't download high resolution for new videos

### ISSUE THREAD

**Issue by umutambyi-gad** [pytube/pytube#954]
I automated script for downloading NBA all stars game highlight last night with the following code
```
...
url = 'https://www.youtube.com/watch?v=v0Fi_nkUH_4'
youtube = YouTube(url)
youtube.streams.first().download()
...
```
but in the morning I realize that I don't have the highest resolution as I expected it when I added this line of code
```
streams.first()
```
now I got `360p` and `720p` was available.
same to all new videos I downloaded.
Thanks in advance

**Comment by tfdahlin** [comment]
hi @umutambyi-gad, there are two reasons that this wouldn't get you the highest resolution.
1) `streams.first()` does not necessarily return the highest resolution result, just the first one that's listed. I believe this is usually a progressive stream, which means that the highest resolution you'll be getting most of the time is 720p, just because of the way that YouTube orders the streams, but could be 360p if a very low resolution is available.

2) YouTube has two different types of stream types: DASH and progressive.

DASH streams are designed to allow the browser to adapt the display quality according to your connection, and they have the audio and video split into different streams. They are also the only way that higher resolution streams (anything greater than 720p) are available.

However, because it splits the stream into two files, one for audio and one for video, it means that you need to do some post-processing to combine the audio and video into a single video after the fact. Ffmpeg is the piece of software that most people use for this kind of post-processing, and an example of how you can combine and audio and video file can be found [here](https://superuser.com/a/277667).

It actually looks like the filter function needs to be reworked a little bit to make it easier to fetch the highest quality, which I will try to fix this week. In the meantime, if your goal is to get 720p, try using this instead:
```python
yt = YouTube(url)
yt.streams.get_by_itag(22)
```
Itag 22 is used for 720p progressive streams, and should work for most videos with 720p available.

**Comment by umutambyi-gad** [comment]
Thanks a lot @tfdahlin for your support .

**Comment by tfdahlin** [comment]
Sure thing!
