### ISSUE TITLE
downloaded video has no audio

### ISSUE THREAD

**Issue by vendz** [pytube/pytube#959]
only one audio has `acodec="mp4a.40.2"`. and I can only get audio from that file.

**Comment by tfdahlin** [comment]
Gonna need more information than this to help you out.

Specifically, I need:
1. The version of pytube you have. Run this to find out:
```python
import pytube
print(pytube.__version__)
```
2. The video URL that you're having problems with
3. The code for how you're downloading the video

**Comment by vendz** [comment]
I am using `pytube - 10.5.3`


and this is the code I am using to download the video
```python3
from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=1jmcloqc4yg')
for stream in yt.streams:
    print(stream)
    
print([stream.resolution for stream in yt.streams])
print(f'Downloading... {yt.title}')

yt.streams.filter(mime_type="video/mp4", res="1080p").first().download()   # no audio coming
```

**Comment by tfdahlin** [comment]
Ah, that's the problem. YouTube has two different stream types: progressive and adaptive (or DASH). Anything above 720p is going to be adaptive. In this case, you're asking for a resolution of 1080p, which will always be adaptive. Adaptive streams are split into two components, audio and video, so if you're downloading a high resolution video, you will need to download the audio separately, and then combine the files. Ffmpeg is probably the piece of software that you want to use for this, and you can find details about how to use it to merge audio and video files [here](https://superuser.com/a/277667).

Alternatively, you can choose to download a slightly lower quality video and find a progressive stream that has both the audio and video in 1 file. Usually, the best way to do this is to ask for itag 22 like this:
```python
from pytube import YouTube
yt = YouTube(video_url)
yt.streams.get_by_itag(22).download()
```

Assuming the video has a stream with itag 22 available, this will give you a 720p video file with audio attached. If you're interested in finding out more about different types of itags youtube uses, you might want to look at [this](https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f). 

Eventually, we're hoping to implement a better system for filtering videos as well, since the current one isn't quite as good as it could be, but that's going to take a while to get to.

**Comment by vendz** [comment]
But ffmpeg doesn't work smoothly on mac

**Comment by tfdahlin** [comment]
I can't really help you with that, unfortunately. If you want to use only pytube, you'll be stuck with 720p quality as the highest you can go without having separate audio and video tracks. Otherwise, you can look into other software to combine audio and video tracks, or you can try and get ffmpeg working, but we can't really help you much with that here.

**Comment by vendz** [comment]
Alright thanks
